Kitware/dive

README.md
client/src/components/NavigationBar.vue
client/src/components/UserGuideButton.vue
client/src/views/Viewer.vue

Also adds linting fixes to README.md.  No changes to README appearance.

Add user guide button

---

client/src/components/NavigationBar.vue
client/src/components/controls/LineChart.vue
client/src/components/layers/EditAnnotationLayer.vue
client/src/use/useEventChart.js
client/src/use/useLineChart.js
client/src/use/useMarkerLayer.js
client/src/use/useTextLayer.js
client/src/use/useTrackFilterControls.js
client/src/views/Viewer/Viewer.vue

The biggest thing here is probably replacing the arrow function in Linechart.vue with a named function.  This is to provide the d3.mouse(this) function with the proper 'this' context.  There is another way but it may require messing with babel/webpack settings to be done properly.  The original comment can be found  [HERE](https://github.com/VIAME/VIAME-Web/pull/29#discussion_r408366847)
The only other larger thing was modifying the useEventChart, useMarkerLayer and useTextLayer to have similar checking for the `filteredDetections.value.length` and for them to have similar return values.  All of their components expect to have Arrays.

Minor code updates

---

client/src/common/api.js
client/src/common/utils.js
client/src/common/viame.service.js
client/src/common/viameDetection.service.js
client/src/components/Export.vue
client/src/components/Upload.vue
client/src/components/UserGuideDialog.vue
client/src/constants.js
client/src/use/useGirderDataset.js
client/src/views/Home.vue
server/README.md
server/viame_server/event.py
server/viame_server/utils.py
server/viame_server/viame_detection.py

This was surprisingly nontrivial.
* Includes a fair amount of refactoring in Home.vue because if I don't do stuff like that during feature work, I won't do it at all.  I wish we had more time for general code quality work, but taxing features / bug fixes with code quality is doable, IMO.
* Still an issue right now where, if a folder doesn't have detections, you get an unfriendly error message.
fixes #107

107 enable download of independent parts

---

client/src/common/viame.service.js
client/src/components/RunPipelineMenu.vue
client/src/store.js
client/src/views/Home.vue
server/viame_server/__init__.py

fixes #111
based on #115, will need to rebase

111 pipeline menu

---

client/src/components/TrackList.vue
client/src/use/useTrackStore.spec.ts
client/src/use/useTrackStore.ts
client/src/views/TrackViewer/Layers.vue
client/src/views/TrackViewer/Sidebar.vue
client/src/views/TrackViewer/Viewer.vue

* Fix de-selection behavior when `escape` is pressed.
* Add `n` key to create new track
* Remember last used track category, automatically populate new tracks with last used.

Fix escape bug, minor refactor

---

client/src/components/CreationMode.vue
client/src/use/useModeManager.ts
client/src/use/useTrackStore.spec.ts
client/src/use/useTrackStore.ts
client/src/views/TrackViewer/Viewer.vue

This is just some style nits that I thought it would be easier to add here.
The only actual functional change I made was to move the `newTrackType` string into `useModeManager.`
I did this before arriving at the conclusions in my other notes, but either way, that variable doesn't belong in `useTrackStore` anymore.

Minor nits

---

client/src/components/TrackItem.vue
client/src/components/TrackList.vue
client/src/lib/track.ts
client/src/lib/vue-utilities/prompt-service/Prompt.vue
client/src/use/useTrackStore.ts
client/src/views/TrackViewer/Sidebar.vue
client/src/views/TrackViewer/Viewer.vue

Will conflict just a bit with #165, but not too bad.
Resolves #67

Split tracks

---

.env
README.md
docker/docker-compose.yml

For @mattrix27 and @AlmightyYakob

Parameterize nvidia docker options

---

README.md
docker/docker-compose.yml

This will change once we get access to the proper kitware org repos, but otherwise this is all I intend to do for #119 
fixes #119

Reference published DockerHub images

---

client/src/components/Export.vue

Change Export to Download

---

client/src/components/TrackList.vue
client/src/utils.ts

Clicking on the globe to go to the root was broken.  
Fixes #179

Fix root browser

---

client/src/views/Login.vue

#145 update splash

---

client/src/components/AttributesPanel.vue
client/src/components/CreationMode.vue
client/src/components/TooltipButton.vue
client/src/components/TrackItem.vue
client/src/components/TrackList.vue
client/src/components/controls/EventChart.vue
client/src/components/controls/Timeline.vue
client/src/lib/listUtils.ts
client/src/lib/track.ts
client/src/lib/utils.ts
client/src/plugins/vuetify.js
client/src/use/useEventChart.ts
client/src/use/useFeaturePointing.ts
client/src/use/useModeManager.ts
client/src/use/useSettings.ts
client/src/views/Login.vue
client/src/views/TrackViewer/ControlsContainer.vue
client/src/views/TrackViewer/Layers.vue
client/src/views/TrackViewer/Sidebar.vue
client/src/views/TrackViewer/Viewer.vue
server/viame_server/serializers/models.py
server/viame_server/serializers/viame.py

Interpolation support

---

client/src/components/Upload.vue
client/src/lib/api/viame.service.ts
client/src/store/Filetypes.ts

I took a look at your issue and this code is working for me.   Does this make sense, or am I missing something?

Suggestion for any type

---

client/src/components/TrackList.vue
client/src/components/UserGuideDialog.vue
client/src/use/useEventChart.ts
client/src/use/useLineChart.ts
client/src/use/useTrackFilters.ts
client/src/use/useTrackSelectionControls.spec.ts
client/src/use/useTrackSelectionControls.ts
client/src/use/useTrackStore.spec.ts
client/src/use/useTrackStore.ts
client/src/views/TrackViewer/Layers.vue
client/src/views/TrackViewer/Sidebar.vue
client/src/views/TrackViewer/Viewer.vue

Semi-invasive update, generally reduces complexity, drops about 50 LoC.
Fixes #193

Use track lists directly #193

---

client/src/components/RunPipelineMenu.vue
server/viame_server/__init__.py

Fixes #112.
Can't really be tested until the update mentioned in that issue adds those pipelines. @mattdawkins whenever that happens please let me know.

Add generate_ pattern to allowed pipelines

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add issue templates for better bug reporting and feature request clarity.

Add issue templates

---

server/viame_server/event.py

Small fix for imports, we had not updated this function to add `annotate: True` to the folder metadata. It also uses the general `csvRegex` instead of looking for exactly `annotations.csv`.

Fix folder metadata on import, use utils.csvRegex

---

.github/workflows/blank.yml
server/dev-requirements.txt
server/pyproject.toml
server/setup.py
server/tests/test_deserialize_viame_csv.py
server/tests/test_serialize_viame_csv.py
server/viame_server/serializers/meva.py
server/viame_server/serializers/models.py
server/viame_server/serializers/viame.py
server/viame_server/utils.py
server/viame_server/viame.py
server/viame_server/viame_detection.py
server/viame_tasks/tasks.py

Prevent merge if linting and import sorting aren't done.
This also cleans up missed linter and sorter issues, so it might have to wait for other server PRs to merge to avoid conflicts.

Add linting and import sort to CI

---

client/app/recipes/headtail.ts
client/app/views/Home.vue
server/viame_server/viame_detection.py

fixes #335  500 Error on detection load      (bug)          about 57 minutes ago
fixes  #332  [BUG] When drawing a line do...  (bug)          about 5 hours ago
fixes  #328  [BUG] Invalid .zip received ...  (bug)          about 2 days ago
﻿
Here are the sizes of the new box.
```
[-0.1, -0.3],
[-0.1, 0.3],
[1.1, -0.3],
[1.1, 0.3],
[-0.1, -0.3],
```
In other words, 1/10th length of line padding in line vector, 3/10th length in perpendicular vector.

Various small fixes

---

client/app/views/Login.vue

Fixes #297

---

client/app/components/RunPipelineMenu.vue
client/app/components/RunTrainingMenu.vue
client/app/use/useSave.ts
client/app/views/TrackViewer/Viewer.vue
server/viame_server/viame.py
server/viame_server/viame_detection.py

Just an update to this branch to fix the access issues.

Access Training/pipeline/saving fix

---

client/app/use/useModeManager.ts
client/app/views/TrackViewer/Viewer.vue
client/src/layers/EditAnnotationLayer.ts
client/src/use/useTrackFilters.ts

Just a couple small backlog issues.  Trying to clear some of the items in the task list before tackling bigger issues.
Let me know if you have a better way to detect a 0 feature track or if you think the escapeMode shouldn't be it's own handler?
I would attempt to use the line drawing mode and the polygon mode without that `setTimeout` and pay attention to the difference between clicking fast and holding the mouse button down.
Fixes #370 
Fixes #359 
Fixes #342

Small backlog issues

---

docker/girder.Dockerfile

This fixes the builds failing due to the changed yarn build command in #383.

Fix docker builds

---

.github/workflows/blank.yml
client/package.json
client/src/components/TrackItem.vue
client/src/components/annotators/ImageAnnotator.vue
client/src/components/annotators/VideoAnnotator.vue
client/src/components/controls/Controls.vue
client/src/components/controls/EventChart.vue
client/src/components/controls/LineChart.vue
client/src/components/controls/TimelineWrapper.vue
client/viame-web-common/recipes/headtail.ts
client/yarn.lock

use https://github.com/Yuyz0112/vue-type-check  for template linting in `src/`
If we like this idea, I'll expand it to other source code, but `src/` is currently the most critical.

Lint templates with vue-type-check

---

.github/workflows/blank.yml
client/package.json
client/src/components/TrackItem.vue
client/src/components/annotators/ImageAnnotator.vue
client/src/components/annotators/VideoAnnotator.vue
client/src/components/controls/Controls.vue
client/src/components/controls/EventChart.vue
client/src/components/controls/LineChart.vue
client/src/components/controls/TimelineWrapper.vue
client/yarn.lock

Lint templates

---

client/src/components/TrackItem.vue

Fixes #404

---

client/src/components/TrackItem.vue

Oops:
https://github.com/VIAME/VIAME-Web/commit/80483a9f7ff0b1f3f5c58bb0b44bbcc9700f85e7
https://github.com/VIAME/VIAME-Web/blob/master/client/src/components/TrackItem.vue#L130L141
Demonstrated need for #410

Fix toggleKeyframe regression introduced in #361

---

docker/ansible/viame-deploy.timer
docker/girder_worker.Dockerfile

Update Deployment and Worker Base Image

---

docker/ansible/deploy.yml

Fix deploy.yml

---

client/README.md

Fix typo in library README

---

client/checkbuild.sh
client/package.json
client/platform/desktop/backend/serializers/cli.ts
client/src/use/useStyling.ts
client/yarn.lock

Fixes uploader performance concurrency bug.

Upgrade GWC 2.2.8

---

server/viame_server/viame.py
server/viame_tasks/utils.py

* Bump token expiration
* Critical training fix to ignore commented lines.

Exclude comment lines, token expiry

---

client/platform/web-girder/views/NavigationBar.vue

Very simple, adds in the fall through for the Cancelling status.

navBar Cancelling

---

client/platform/web-girder/views/NavigationBar.vue
server/viame_tasks/tasks.py
server/viame_tasks/utils.py

Cancel Jobs

---

server/viame_tasks/utils.py

Infinite loop

---

client/src/components/annotators/ImageAnnotator.vue

Hopefully this shouldn't have any adverse effects.  It looks like playing and loading still works properly.  There may be one corner case in that if you are playing and subbing at the same time it may revert back to loading the cache around you instead of the current frame.
`lastFrame` is set to -1 so the initial seek loads the first frame properly.

Cache improvements

---

docker/ansible/README.md
docker/ansible/deploy.yml

This is another change to fix our deployment. The explanation is shown in the change to `docker/ansible/README.md`.

Change volume name in deploy.yml, update README

---

server/viame_server/viame.py

I'm testing this locally while CI runs.

Lazy load pipelines

---

docs/index.md

Explain DIVE and VIAME

---

docker/girder_worker.Dockerfile

Compensates for a change in the base image.

Change owner of opt user viame

---

client/platform/desktop/backend/ipcService.ts
client/platform/desktop/backend/native/common.ts
client/platform/desktop/backend/serializers/viame.ts
client/platform/desktop/constants.ts
client/platform/desktop/frontend/api.ts
client/platform/desktop/frontend/components/Export.vue
client/platform/desktop/frontend/components/NavigationBar.vue
client/platform/desktop/frontend/components/ViewerLoader.vue
client/viame-web-common/components/Viewer.vue

Export CSV

---

client/viame-web-common/components/RunPipelineMenu.vue

Please scrutinize and change, I did this quickly and may not have done the most thorough checking on it.

pipeline list css changes

---

docker/girder.Dockerfile
docker/girder_worker.Dockerfile

Fixes for https://github.com/pyca/cryptography/issues/5771
Also re-ordered for cache optimization.  things that change less frequently should happen earlier in build.

Optimize docker build

---

client/platform/desktop/backend/native/attributeProcessor.ts

See recent email thread.
Detection attributes were being missed on ingestion.

[Critical] Attribute processing bug

---

client/dive-common/use/useModeManager.ts
client/src/use/useTrackStore.ts

Proper insert location and delete selection behavior

---

CONTRIBUTING.md

Some updates to our team process.

Formalize workflow

---

docker/docker-compose.prod.yml

I forgot this is the golang 6-field cron timer.
https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format

Fix Cron schedule

---

server/dive_server/viame_detection.py

Fixes #638 Image Sequence download broken

---

client/public/index.html

Show no title unitl brand data load

---

client/dive-common/components/AttributesSubsection.vue
client/platform/desktop/frontend/components/NavigationBar.vue
client/platform/desktop/frontend/components/ViewerLoader.vue
client/src/components/TrackList.vue
client/src/components/TypeList.vue

Icon change from MDI upgrade

---

client/platform/desktop/frontend/components/Recent.vue

Text search over all datasets.

Add simple search feature on recents page

---

docs/Dive-Desktop.md
docs/Web-Version.md

Document transcoding conditions

---

client/dive-common/components/Viewer.vue
client/src/use/useTrackStore.ts

Fixes #731 
Issue with saving after splitting tracks.

Insert bugFix 

---

client/package.json
client/vue.config.js
client/yarn.lock

Bump versions

---

client/package.json
client/platform/desktop/background.ts

Release 1.4.6

---

server/dive_server/viame_detection.py

Fixed detection csv names when downloading

---

client/platform/desktop/backend/serializers/viame.ts
server/dive_server/serializers/viame.py

Fixed loading error for csv files without object types

---

devops/.gitignore
devops/ansible/playbook.yml
devops/inventory.local
devops/main.tf
docker/README.md
docs/Google-Cloud.md

Tested working on CPU nodes in google cloud.

Update google cloud docs, ansible scripts

---

devops/ansible/playbook.yml
devops/main.tf
docs/Google-Cloud.md

Finally able to test with GPU, switched instance type.

Switch to N1 and Nvidia T4 defaults

---

client/dive-common/components/UserGuideDialog.vue

Added arrow keys for frame changing in quick help

---

client/platform/web-girder/views/Home.vue

Simple bug.  promptShow didn't return the awaited value.  Remove function, pass prompt direclty.

Fix prompt delete

---

client/package.json

Mostly so Roddy can use the new import feature.
When should we go to 1.5.0?

Release 1.4.10

---

server/dive_tasks/manager.py

Silly mistake in monkey patch.
fixes #809

Patch job manager

---

client/dive-common/apispec.ts
client/dive-common/components/AttributesSubsection.vue
client/dive-common/components/TrackDetailsPanel.vue
client/dive-common/components/Viewer.vue
client/dive-common/use/useModeManager.ts
client/src/components/LayerManager.vue
client/src/components/TrackItem.vue
client/src/components/TrackList.vue
client/src/components/annotators/ImageAnnotator.vue
client/src/components/annotators/VideoAnnotator.vue
client/src/components/annotators/mediaControllerType.ts
client/src/components/annotators/useMediaController.ts
client/src/components/controls/Controls.vue
client/src/components/controls/FileNameTimeDisplay.vue
client/src/provides.ts
client/src/track.ts
client/src/use/index.ts
client/src/use/useTimeObserver.ts
docs/FAQ.md
mkdocs.yml
server/tox.ini

Verification data:
* https://viame.kitware.com/#/viewer/60cc7899d8b8a2b39c3bd4b1
* https://viame.kitware.com/#/viewer/6074b9b0244544940f7755f9

Frame Alignment Improvements.

---

client/dive-common/components/Viewer.vue
client/platform/desktop/frontend/components/Settings.vue
client/platform/desktop/frontend/components/ViewerLoader.vue
client/platform/desktop/frontend/store/index.ts
client/platform/desktop/frontend/store/settings.ts

Updates for Farhan's branch.
* Report true null type for uninitialized settings
* Fix race conditions for reloading settings and viewer.

env-overrides updates: Report true null, fix race conditions c3a5265

---

client/package.json

Release once everything else is ready.

release 1.6.0

---

server/dive_utils/serializers/kwcoco.py

small changes for the kwcoco stuff.  Removes some errors that were being seen before.

kw-poly-fix

---

server/dive_tasks/frame_alignment.py
server/dive_tasks/tasks.py
server/dive_tasks/utils.py

It's all a bunch of indentation changes, but git aligned them badly, so it looks like a huge diff.
fixes #905

Fix 905 only use context managers for temporary folders.

---

server/dive_tasks/tasks.py
server/dive_utils/models.py
server/tests/integration/conftest.py
server/tests/integration/test_dataset_operations.py
server/tests/integration/test_dataset_upload.py
server/tests/integration/test_download_extract.py

Allows the framerate to be a floating point number.

Reverse casting order

---

client/platform/desktop/backend/native/common.ts
client/platform/desktop/frontend/components/ImportDialog.vue

Remove FPS floor on ingest, allow user to choose native FPS.

Allow raw FPS on the client

---

client/dive-common/components/ConfidenceFilter.vue
client/dive-common/components/Sidebar.vue
client/dive-common/components/SidebarContext.vue
client/dive-common/components/TrackSettingsPanel.vue
client/dive-common/components/TypeThreshold.vue
client/dive-common/components/Viewer.vue
client/dive-common/store/context.ts
client/platform/desktop/App.vue
client/platform/desktop/backend/native/common.ts
client/src/components/TypeList.vue
client/src/components/annotators/VideoAnnotator.vue
client/src/provides.ts
client/src/use/useTrackFilters.ts

Per-Type Confidence Thresholds

---

server/dive_server/crud_dataset.py

I want to add integration tests for this

[Critical] Fix attribute patch

---

client/platform/web-girder/views/Export.vue
server/README.md
server/dive_server/crud.py
server/dive_server/crud_rpc.py
server/dive_server/views_dataset.py
server/dive_tasks/tasks.py
server/dive_utils/models.py
server/dive_utils/serializers/kwcoco.py
server/tests/integration/conftest.py
server/tests/integration/test_dataset_operations.py
server/tests/integration/test_dataset_upload.py
server/tests/integration/test_pipelines.py
testutils/example.config.json

* Replace 5 functions for loading various data types with 2 more general_purpose ones.
* Introduce FileType enum
* Import/Export of dataset configuration
* Integration tests for new endpoint
* Add some integration tests for running pipeline since this code touches postprocessing.
Fixes #884

Add import export feature with tests

---

client/src/components/annotators/ImageAnnotator.vue
client/src/components/annotators/VideoAnnotator.vue

This arose from a request in a downstream project. I've tested this with `ImageAnnotator.vue` and it works as expected. I haven't tested it with `VideoAnnotator.vue`, so I can't explicitly verify that functionality, although I'd expect it to work just the same.
I also realize this might not be in line with the existing coding style / organization, so please point out / suggest these fixes if they apply.
related to #600

Add brightness prop and svg filter

---

client/platform/web-girder/views/Jobs.vue
devops/README.md
docker/docker-compose.yml
server/bucket_notifications/README.md
server/dive_tasks/celeryconfig.py

Reverts Kitware/dive#997
fixes #995

Revert "Remove private jobs"

---

.github/workflows/blank.yml
client/package.json
client/vue.config.js
client/yarn.lock

This turned out to be quite simple
fixes #974

Publish source maps to Sentry Release during GitHub Actions Run

---

client/dive-common/use/useModeManager.ts

Fix #1058 - disable delete confirmation during track merge.

---

client/platform/web-girder/views/DataBrowser.vue
client/platform/web-girder/views/DataShared.vue

OpenClip is not a function

---

client/platform/web-girder/views/DataBrowser.vue

* Event handler for job status changes was unhooked
* handleNotification was dead code
* event bus needed to be unsubscribed on unmount.

Data Browser refresh bug on transcoding completion

---

server/setup.py

Updating the girder version fixes our build.

update girder to current viable version

---

docs/Deployment-Docker-Compose.md
docs/Deployment-Provision.md

Update docker deployment guide

---

client/dive-common/components/Viewer.vue

fixes #1185 
Should be all that is needed to fix this.

Fix Track Trails support

---

client/package.json
client/platform/web-girder/views/Clone.vue
client/platform/web-girder/views/DataBrowser.vue
client/yarn.lock

Adapt to https://github.com/girder/girder_web_components/releases/tag/v3.2.0

Upgrade GWC

---

client/platform/web-girder/views/DataBrowser.vue
docker-compose.override.yml
docker/server_setup.py
server/dive_server/crud.py
server/dive_server/crud_dataset.py
server/dive_server/crud_rpc.py
server/dive_server/views_dataset.py

* move `meta.foreign_media_id` to `foreign_media_id`
* Migrate
* Expose new field from folder
* Respect range headers in media download.

Clone key migration and download ranges

---

client/dive-common/components/EditorMenu.vue
client/dive-common/components/GroupSidebar.vue
client/dive-common/components/RangeEditor.vue
client/dive-common/components/Sidebar.vue
client/dive-common/components/TrackDetailsPanel.vue
client/dive-common/components/Viewer.vue
client/dive-common/store/context.ts
client/dive-common/store/settings.ts
client/dive-common/use/useModeManager.ts
client/platform/desktop/frontend/store/index.ts
client/src/Group.ts
client/src/GroupStore.ts
client/src/StyleManager.ts
client/src/components/FilterList.vue
client/src/components/GroupEditor.vue
client/src/components/GroupItem.vue
client/src/components/GroupList.vue
client/src/components/LayerManager.vue
client/src/components/TooltipButton.vue
client/src/components/TrackItem.vue
client/src/components/TrackList.vue
client/src/components/TypeEditor.vue
client/src/components/TypePicker.vue
client/src/components/controls/EventChart.vue
client/src/components/styles/common.scss
client/src/provides.ts
client/src/use/useEventChart.ts

Things are getting easier now!  
* This pull request introduces the ability to create activity groups using multi-select.
* It also fixes the issue with group type editing to make the group style editor work.
https://user-images.githubusercontent.com/4214172/166807083-70cd0588-b5ff-4595-82aa-b1962b800566.mp4
part of #850

Group Creation

---

client/platform/web-girder/api/annotation.service.ts
client/platform/web-girder/router.ts
client/platform/web-girder/views/Summary.vue
client/src/use/useStyling.ts

Adds an expandable table for label stats. Chips launch annotator for corresponding Dataset.
fixes #1158

Stats page table

---

docs/Deployment-Docker-Compose.md
server/dive_tasks/tasks.py

Addon upgrades may 2022

---

client/package.json

Release 1.9.0

---

client/dive-common/components/ControlsContainer.vue
client/dive-common/components/MultiCamTools.vue
client/dive-common/components/Sidebar.vue
client/dive-common/components/TrackDetailsPanel.vue
client/dive-common/components/Viewer.vue
client/dive-common/use/useModeManager.ts
client/src/CameraStore.ts
client/src/TrackFilterControls.spec.ts
client/src/components/GroupList.vue
client/src/components/LayerManager.vue

No canary in CameraStore

---

client/platform/desktop/backend/native/viame.ts

Missing newline in training that involves video....

Training video bugfix

---

server/dive_tasks/tasks.py

Fixes the URLS for add-ons by updating them to the latest
#1274 - some additional information in this issue

fixing URLS for addons

---

docs/Deployment-Overview.md
docs/Deployment-Storage.md
server/README.md
server/tox.ini

Small documentation update
Also adds the ability to build the docs directly in poetry with some update to the corresponding README as well.

adding ability to build docs in poetry

---

client/src/use/useEventChart.ts

Event Color wasn't updating properly, this will fix the issue.

fix event color regression

---

client/dive-common/components/Viewer.vue
client/platform/web-girder/router.ts
client/platform/web-girder/views/AnnotationTags.vue
client/platform/web-girder/views/ViewerLoader.vue
client/src/StyleManager.ts
client/src/components/LayerManager.vue
client/src/components/TrackItem.vue
client/src/layers/AnnotationLayers/OverlapLayer.ts
client/src/layers/AnnotationLayers/PolygonLayer.ts
client/src/layers/AnnotationLayers/RectangleLayer.ts
client/src/layers/AnnotationLayers/TextLayer.ts
client/src/layers/BaseLayer.ts
client/src/layers/LayerTypes.ts
client/src/provides.ts
client/src/track.ts

resolves #1379 
Uses the renamed 'Sets' and creates the tools for comparing annotations in a simple way of overlapping annotations having the area filled in with the track type with 20% opacity.

Set Comparison Tool

---

server/dive_utils/serializers/viame.py

Updates frame order to allow FishTrack23 imports.

update frame ordering algos

---

.github/workflows/blank.yml
client/src/components/annotators/useMediaController.ts
server/README.md
server/poetry.lock

adjust max zoom level to 32 for all maps

---

client/platform/desktop/backend/native/common.ts
client/platform/desktop/backend/serializers/viame.ts
client/platform/desktop/constants.ts
client/platform/desktop/frontend/components/Settings.vue
docker/girder_worker.Dockerfile
server/dive_server/crud_dataset.py

resolves #1473  - Desktop Readonly Mode button being enabled before completion of setting
resolves #1483  - Tiled Image downloading support
Began adding in #1489 - Added functionality for exec_time recording and output in CSV files but haven't tested it yet.

Swap to kitware:gpu-algorithms-web tag for base Worker Branch
