client/package.json, client/src/components/TrackItem.vue, client/src/components/Tracks.vue, client/src/plugins/vuetify.js
- **package.json**  - Downgrade of the vue-virtual-scroll-list to fix a bug in which it was continually calling getItemProps and rendering the list even with no actual changes. see [vue-virtual-scroll-list issue 146](https://github.com/tangbc/vue-virtual-scroll-list/issues/146).
- **Vuetify.config edit** - Enabled the custom properties to directly access theme colors/styling as css vars, to ensure that highlighting matches the current theme.
- **selectedOffset computed property** to figure out the offset in virtual list to scroll to.  This is where things might need to change in the future.  Doing a map and indexOf each time you change the selection could be costly on extremely long lists of tracks.  It might make sense to create a HashMap of the track list with the key being the ID and …
=> Highlighting and scrolling to selected tracks

client/src/components/AnnotationLayer.vue, client/src/components/AttributeInput.vue, client/src/components/EditAnnotationLayer.vue, client/src/components/ImageAnnotator.vue, client/src/components/Upload.vue, client/src/components/VideoAnnotator.vue, client/src/components/timeline/LineChart.vue, client/src/components/timeline/Timeline.vue, client/src/views/Viewer.vue
Adds ability to annotation head and tail independently
* removes `f` and `d` keybindings for annotation
* adds `g` and `h` keybindings for head annotation (right and left handed)
* adds `t` and `y` keybindings for tail annotation (...)
* adds `f` and `d` keybindings for +1 frame and -1 frame (standard video interface UI/UX)
* adds `q` for delete head/tail annotations.
Press g, h, t, or y to start an annotation.  
* if neither exists, you will be prompted to provide both, starting with the key you pressed.
* if you don't want to provide both, tap any of the keys to exit the edit state.
* if both (or one) already exists, you will only be prompted to provide the one corresponding to the key you pressed
PR also cleans up some `console.log` lines and adds comments denoting code quality issues. …
=> [feature] allow independent head and tail track annotations

client/package.json, client/src/components/Upload.vue
Changes
- Added default FPS to 10 when uploading files
- Added in default upload Folder name, based on the first file in the list and removing the extension
- Changed 'Upload' to 'Start Upload', multiple times I got confused and clicked 'Upload' thinking it would allow me to add more files
- Implemented the fileUploader mixin from Girder Web Components
- Image counter now decreases as the images are uploading.  That was the original intention of how this component was designed, it didn't work properly because of the batch uploading (instantly tried uploading 500 items).
- If the upload is a single file, it will display the file size
- If the upload is a list of videos it will display the number, then when it starts uploading it will display the current amount of data uploaded and the …
=> [enhancement] upload progress fixes

client/src/components/ImageAnnotator.vue, client/src/components/Upload.vue, client/src/views/Home.vue, client/src/views/Viewer.vue, server/viame_server/__init__.py, server/viame_server/event.py, server/viame_server/utils.py, server/viame_server/viame.py, server/viame_server/viame_detection.py
This addresses the major concern raised by @mattdawkins. The diff is fairly large, as there needed to be several changes to get this to work, including fixing usability.
=> Allow for annotating image-sequences when annotations not already present

client/src/components/AnnotationLayer.vue, client/src/components/TrackItem.vue, client/src/components/Upload.vue, client/src/components/timeline/EventChart.vue, client/src/plugins/vuetify.js, client/src/views/Viewer.vue
When other PRs are done I'll rebase to the latest:
- Changed default styling to use some more muted blue colors for the accent and base primary color.  This is mainly seen in the login screen and some of the highlights in the system.
Old Color: 
New Color:
- Modified the default colors for types to be a list of Vuetify colors that had been slightly desaturated.  To much muting makes it harder to tell the difference between them.  
- Swapped the 'lime' highlight to using the vuetify accent color.  This is consistent with the highlighting of the track item in the list.  Makes it consistent that a highlighted or selected item in VIAME-Web utilizes the Vuetify accent color to indicate that it is selected.
- To indicate a highlighted track I added a selected (boolean) properly to the …
=> Changing Default Styling

client/src/components/Upload.vue
fixes #18 and fixes #19 
Adds the ability to create a folder or to rename a single file when it is uploaded.  
- You can upload multiple files and specify the folder name
- You can upload multiple files into the current folder - then default filenames are used
- You can upload a single file and specify a new name if you want.
- 
If you choose a single file, the file name is preselected with the extension.
Foldernames default to the first filename in the list minus the extension.  I don't know if an easy way to get the parent folder from an input dialog for a collection of files.
=> Create folder option

client/src/components/TrackItem.vue, client/src/components/TypeList.vue, client/src/components/Upload.vue, client/src/plugins/vuetify.js
Makes checkboxes white instead of blue, because blue's meaning is already used for "individual track selection" so having it on label and track toggles confuses that meaning.
Uses config merge strategy described in https://github.com/girder/girder_web_components#customizing-vuetify-configuration
fixes #34
=> [bugfix] resolve color contrast issues

client/src/components/annotators/annotator.js, client/src/components/layers/EditAnnotationLayer.vue, client/src/use/useSave.js, client/src/views/Viewer/Viewer.vue
When you edit an annotation, then change the current frame, the annotation is lost.  IMO, this is a large usability bug. This change makes it so frame-changes add annotation modifications to the queue and cause the save button to appear.
Workflow becomes: adjust, press f, adjust, press f...
Adds a badge on the save icon to show how many outstanding changes are currently unsaved.
=> Persist annotations

.dockerignore, README.md, client/vue.config.js, docker/girder.Dockerfile
This fixes the issues with docker build and shrinks the docker image down to a reasonableish 600MB.
We will be able to get a much smaller one in the near future.
=> Shrink dockerfile, fix issue with docker build

client/src/components/Upload.vue, client/src/views/Home.vue
There were a fair number of bugs I found while testing your branch. 
* Uploading images and video at the same time silently omits either video or images depending on what appears first in the list.  Now, it throws an error
* Ability to choose to create subfolders removed.  Now, it's totally deterministic and only happens when multiple videos are uploaded.  Taking this choice away from the user I think is good.
* Errors used to be duplicated since there is only 1 instance of `errorMessage`.  I've dealt with this by moving error reporting out of the `v-for` and having it tied exclusively to the first item in the pendingUpload list (see below)
* Errors during upload could get you stuck in an infinite loop (the while loop) since nothing gets dequeueud when an error is thrown.  This was fixed …
=> Fixes for subfolders

client/src/components/Upload.vue, client/src/views/Home.vue
fixes #41 
Swapped the 'create Folder' checkbox to be a dropdown allowing the user to choose between:
- Folder (creation of a folder for the files)
- Current (upload files to the current location)
- Subfolder (create a subfolder for each file)
It will check the uploaded files and try to determine automatically which mode to select.
Structural changes to upload.vue:
- created regular expressions for filtering Images and Video files.  They are used in a few places so figured abstract that out.
- added in the upload location types
- Added in suggested upload location based on files
- Split the pendingUpload function into folder creation and file upload.  This was necessary to support the subfolders.  I wanted to use the existing functionality of the uploadMixin and the fact that the existing …
=> Creation of subfolders while uploading

client/src/use/useGirderDataset.js, client/src/views/Home.vue, server/viame_server/__init__.py, server/viame_server/event.py, server/viame_server/utils.py, server/viame_server/viame_detection.py
This PR does two main things:
1. Updates the event listener to add the annotate metadata when uploading a video, as well as an image
2. Changes the metadata on folders/items, to work in a more sensible way. 
Now, the metadata structure is as follows:
* Folders have a metadata structure of:
```
annotate: true | false
fps: Int
type: "video" | "image-sequence"
viame: true
```
* Result detection items have a metadata structure of:
```
detection: <folderId>
```
The value of the detection field represents the folder to which the detections belong. Ideally, I think to keep track of videos more appropriately, we should find a way to set a "video" field on the folder metadata, with the item ID of the video for that folder. However, that's not possible with our current event listeners, as the event …
=> Fix video annotation/detection

client/src/components/TrackItem.vue
When a user highlights a track and presses `shift-enter` the enter into edit mode for the combo box.
Currently, there's no way out without using the mouse.  With this change, selection of a different label with arrow keys + enter will exit edit mode and allow the user to continue navigating the list.
To edit the text by typing a new label, `shift-enter` enables typing.   `escape` will close the dropdown without exiting edit mode.  `enter` exits edit mode and returns control to the track list.
=> Ability to get un-stuck from editing combobox with keyboard

README.md, client/src/components/NavigationBar.vue
Log out is currently boroken.  
I tacked a small docs update onto this because I spoke with someone who just wanted a way to view KW18 files on their videos, and pulling/building 15GB just to have it sit idle seems like a waste.
=> [bugfix] log out

client/src/components/Upload.vue, server/viame_server/utils.py, server/viame_server/viame.py, server/viame_tasks/tasks.py
Fixes #48.
This exposes an endpoint `/viame/image_conversion`, that will convert all images within the specified folder to a web friendly format (currently `.png`, but we might want to change that to `.jpg` for saved bandwidth.
One thing this does is replaces the files in the specified folder with the converted files, if the conversion succeeds. We could do this immutably, but I wasn't sure if that was desired, so I didn't initially include it. 
This is also hooked up to the front-end, so when uploading files, it will call that endpoint if there are any files that have image formats which need conversion.
One thing that might be helpful to sync the frontend and backend is an endpoint on the backend that returns the valid image/video formats. If we think this is a good idea we can make a …
=> Add image conversion of non-web-friendly image formats

server/dev-requirements.txt, server/pyproject.toml, server/setup.py, server/viame_server/__init__.py, server/viame_server/client_webroot.py, server/viame_server/event.py, server/viame_server/serializers/viame.py, server/viame_server/transforms.py, server/viame_server/utils.py, server/viame_server/viame.py, server/viame_server/viame_detection.py, server/viame_tasks/__init__.py, server/viame_tasks/tasks.py
Adds `black` and `isort`
The VS Code config to run both of these on save is:
```
{
"python.formatting.provider": "black",
"[python]": {
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
"source.organizeImports": true
}
},
}
```
I also factored the parsing logic out into a serializers subfolder in preparation of #96 and other formats.  I don't think it's great style to do that all in the REST handler anyway.
FWIW, I think 80 char columns is too restrictive.  I prefer 90-100 myself, but ya'll should decide.
resolves #91
=> 91 pyproject black isort

client/src/components/layers/MarkerLayer.vue, client/src/components/layers/TextLayer.vue
The `TextLayer.vue` has a `v-if` tied to the length of the data it receives.  If the data is 0 it won't render.  The Data is also connected to a property which is used inside of `TextLayer.vue` to compute the `frameMap` used to render the page.  When data hits zero it will stop rendering the Vue element but keep the computed data property.  So the GeoJS render still believes that there is text data to display.  I added in a proper Destroy binding as well as removing the `featureLayer` and drawing the screen blank before. I followed a similar beforeDestroy used on the main `AnnotationLayer.vue` and the `EditAnnotationLayer.vue`
`MarkerLayer.vue` had the same issue so I added the fix to it as well.
=> Fixes Persistent text issues

.gitignore, client/src/use/useDetections.js, server/viame_server/serializers/viame.py, server/viame_server/viame_detection.py
Add parameter for server to return JSON list of tracks.   This will support #84, but it's only the first step for that issue.
* It is my intention that the server would eventually save this data straight to a file and serve it to the app, then serialize to the VIAME csv format on demand.
* In order to use this on the client, serialization of this new structure to VIAME csv is still missing.  I think that should be a part of this PR, but I want to get some other eyes on the structure here first.
=> Server-side JSON track processing

client/src/components/RunPipelineMenu.vue, client/src/store.js
Fixes #122 
The previous implementation of pipelines was an empty array (`[]`) by default, that became an object when returned by the axios request.  I switched it to always being an `Object` instead with the default being empty and then sorting before committal.  
The only thing I'm not sure on is if the intended logic for disabling the run pipelines option.  It starts as an array, if you get an error back from axios it doesn't change the result, so the test for `this.pipelines === null` inside of `RunPipeLineMenu.vue` I don't think would ever be reached unless the backend specifically sets the return value to `null`.  
So you would get the ability to open RunPipelines, but have no pipelines available like this: 
My version prevents the Run Pipelines menu option from being enabled if …
=> 122 sort pipelines

server/setup.py, server/viame_server/serializers/viame.py
Fixes #131 
This is a first pass at adding dataclasses, and also adds a bit of abstraction to the operations we're doing. I think this makes it easier to read.
This also adds a good bit of typing information, which I think adds clarity. The main drive for me adding type annotations during this PR was mainly any code that I touched, however I could add more if it's desired. Also, if we generally like this, it might be worth it to add `mypy` or something similar, so we can do static type checking and take full advantage of type hints.
=> Add dataclasses with general abstraction

docker/ansible/README.md, docker/ansible/clean.systemd.yml, docker/ansible/deploy.yml, docker/ansible/main.yml, docker/ansible/systemd.yml, docker/ansible/viame-deploy.service, docker/ansible/viame-deploy.timer
Fixes #36 
Currently, this PR only updates code, and updating `deploy.yml` will have no effect, until updated manually on the server. If this is desired, the `main.yml` playbook would allow for this, as this runs both the systemd playbook, and the deploy playbook. However, the reason I haven't included it here is that I'm not sure if we even need to worry about the `systemd` files changing, and including that would mean that we need to do more work around storing a user's `sudo` password.
=> Add Continuous Deployment

client/src/components/Tracks.vue, client/src/components/annotators/ImageAnnotator.vue, client/src/components/controls/Timeline.vue, client/src/components/layers/AnnotationLayer.vue, client/src/use/useAnnotationLayer.js, client/src/use/useStyling.js, client/src/use/useTextLayer.js, client/src/views/Home.vue, client/src/views/Viewer/Viewer.vue
Fixes #27 
Adds some simple CSS to force the Folder name to wrap instead of the buttons.
I noticed that we do similar css updates to other parts of the GWC in the code so figured it wouldn't be a problem here.
Fixes #28 
This will deselect the current track if the user clicks on any area outside of any detection.
Added a new `geoOn.(geo.event.mouseclick, e)` event handler that will check all clicks and see if there is element under the mouse position.  GeoJS seems to have a built int feature for clicking on features but not for clicking off of one.  We could perhaps refactor this in the future to utilize one mouse event for all elements.  Part of this is also a change to utilizing `annotationClick` to make sure the user isn't editing a feature when they click.
Fixes #129 
I changed the …
=> Various UI Fixes

docker/girder_worker.Dockerfile
This was never bumped in #136, so before this change it failed to build. We might want to consider adding CI that runs the build to ensure it succeeds.
=> Use python3.7 instead of python

client/src/components/TypeList.vue, client/src/views/TrackViewer/Layers.vue, client/src/views/TrackViewer/Sidebar.vue, client/src/views/TrackViewer/Viewer.vue
- Modification to CSS for TypeList hopefully to make it so the TypeList Header is at the top and the items are scrolled instead.
- Added in a check to make sure you don't go into Feature Editing Mode while in the middle of creating a new bounds. 
- Delete Features weren't properly connected to the current frame so they didn't work.  This allows them to work but we need a discussion on notification to updateLayers that the features have been removed.  You can test by deleting now and changing frames to see the delete but we want it to happen in real time.  One option is using the notify on each Selected Track that contains Feature points and if they are deleted. or set to undefined it will update the layer.
=> Minor changes and fixes

client/src/@types/vue-utilities.d.ts, client/src/components/TrackList.vue, client/src/components/controls/Controls.vue, client/src/components/layers/EditAnnotationLayer.ts, client/src/lib/vue-utilities/prompt-service/Prompt.vue, client/src/lib/vue-utilities/prompt-service/index.js, client/src/use/useTrackStore.ts, client/src/views/TrackViewer/Layers.vue, client/src/views/TrackViewer/Viewer.vue
Some additional changes and fixes to the track-centric stuff
- Added in the Prompt - I decided to use the existing style because of the usage in the Home.vue for file deletion.  We can in the future decide to switch this over to a composition function I think fairly easily and then just have it is used by the other items.
- Within Prompt I added Keyboard functions for the focusing of elements.  the `NextTick( () => NextTick())` is done because the element is mounted initially.  It changes visibility on `show` so we need it to mount, then there is a delay then we can focus on the confirm
- Prompt now has a visible() function call to see if the prompt is visible on the screen it is used in v-mousetrap
- mousetrap changes to disable certain keyboard functions if the prompt is visible
- …
=> Updates to fix several issues

client/src/components/TrackList.vue, client/src/components/TypeList.vue, client/src/components/layers/AnnotationLayer.ts, client/src/components/layers/BaseLayer.ts, client/src/components/layers/TextLayer.ts, client/src/use/useEventChart.ts, client/src/use/useGirderDataset.ts, client/src/use/useLineChart.ts, client/src/use/useStyling.ts, client/src/views/TrackViewer/Layers.vue, client/src/views/TrackViewer/Sidebar.vue, client/src/views/TrackViewer/Viewer.vue
* Refactor `typeColorMapper` into more generic `typeStyling` object with coloring function
* Rename that everywher
* Make it reactive, depend on it for other UI componnets.
* Address other style comments from main PR.
=> Refactor reactive typeColorMapper

client/src/@types/girder-components.d.ts, client/src/utils.ts, client/src/views/Home.vue, client/src/views/TrackViewer/Viewer.vue
Fixes #187 
Fixes #188 
The location in the vuex state wasn't working properly with the breadcrumb bar in the file browser.  It required a click on which it would error and then a second click where it would finally change the page.  I updated Home.vue to get rid of the mapping of a location object while also having a computed location object.  This fix should make it work for all of the breadcrumb items as well as  utilizing the back/forward in the browser.
Additionally to this I modified the `Viewer.vue` to check and see if the state `location` variable is set.  If you navigate directly to an annotation link or if you refresh the page you reset and lose that `location` variable and when you click "Data" in the NavBar it takes you back to the root of girder.  I've updated it so it checks …
=> Fix location errors

client/src/components/TrackItem.vue, client/src/components/controls/EventChart.vue, client/src/use/useEventChart.ts
I generally liked what you did here.   This PR makes a few subtle changes.
* Generally clean up logic, add better variable names, comments, etc.  I tried to fill in comments when I spent more than a few seconds thinking "What does this do?"
* Before, a black shade was being drawn that caused conttrast with the rest of the event bar.  It was easier just do not draw the shade and mute the colors of the individual bars, keeping the background transparent.  I found that painting less layers also made things look a little sharper.
* Adds `muted` field to data prop to tell the component when a selected bar is present and the rest should be muted
* Makes the overflow value `0.6` to show feature segments.
* Removed the WidthDivisor bits, since the frame overhang on boundaries gives nice …
=> clean up eventChart code

README.md, docker/README.md, docker/girder.Dockerfile, docker/girder_worker.Dockerfile
New README: https://github.com/VIAME/VIAME-Web/blob/fd6ac189499df3dde555a81badbf246003e4ae1e/README.md
New Docker README: https://github.com/VIAME/VIAME-Web/blob/fd6ac189499df3dde555a81badbf246003e4ae1e/docker/README.md
=> Move docker docs to another README

client/src/components/TypeList.vue, client/src/components/layers/AnnotationLayer.ts, client/src/components/layers/BaseLayer.ts, client/src/components/layers/MarkerLayer.ts, client/src/use/useEventChart.ts, client/src/use/useGirderDataset.ts, client/src/use/useLineChart.ts, client/src/use/useStyling.ts, client/src/views/TrackViewer/Layers.vue, client/src/views/TrackViewer/Sidebar.vue, client/src/views/TrackViewer/Viewer.vue
Allows a user to edit the type styling
- The user can now set per Type: Color, name, opacity, filled, line thickness.
- I've updated the usage of the type styling to be one interface that can be updated in the future with other elements if needed.
- AnnotationLayers have additional styling options added to reflect updates
- Each style item has a function like the color styling before.  If a value doesn't exist it will default back to the standard styling just like before.
- It will load the old style customColors as well as a new style CustomStyles.  I wanted to maintain support in case anyone was using the old way.
- Also added in a method of generating colors right now which utilizes d3's rainbow and then messes with Hue (HSL) values to get a darker and lighter version of each color. …
=> User Edited Type Styling

client/src/components/TrackList.vue, client/src/components/UserGuideDialog.vue
Fixes #200  - changes the detection+ to +detection/track now and reorders where the settings icon is.
Fixes #201  - adds a shortcut key to the inline documentation.  I have a current Google Doc that I need to transfer to the wiki for more in-depth documentation of the entire interface.  Getting this merged first would help with any newer screenshots that are needed.
=> Minor Styling updates

client/src/components/layers/EditAnnotationLayer.ts, client/src/use/useModeManager.ts
This solves the issue of selecting a point and then advancing a frame and still having the "Delete Point" button visible. 
Totally up to you if you want to to accept or go with the other way.  I wasn't thinking properly before and forgot about the disable method available to the `EditAnnotationLayer` and that we can use that as well as the change data to recognize when it changes modes.  I understand if you feel it's clearer to keep the reselection to -1 in the modeManager, but if we do we would need to add a watcher to  the current `frame` to handle when that changes as well.  This should make it so that the Layer is always synced with the property.
=> Cleaning up the selection and deselection of handle indices

client/src/components/Export.vue, client/src/components/RunPipelineMenu.vue, client/src/components/UserGuideButton.vue
Remove button text in toolbar on page breakpoints to make room for the stuff we've added to the toolbar.
Below a certain width, this app becomes useless, so I'm not going to agonize over proper scaling at mobile widths.
=> Hide button text on breakpoints

docker/ansible/.gitignore, docker/ansible/.vars.example.yml, docker/ansible/README.md, docker/ansible/deploy.yml
Fixes #231 
This updates the behavior of the builds to start the service independent of building, so that if it fails, the service can come back online without issue. Furthermore, if the build fails, it will send a failure report to the email address we specify.
=> Continue if build failed, send failure report

client/src/components/TrackItem.vue, client/src/components/annotators/ImageAnnotator.vue, client/src/components/annotators/VideoAnnotator.vue, client/src/components/annotators/annotator.js, client/src/components/controls/Controls.vue, client/src/components/controls/EventChart.vue, client/src/components/controls/LineChart.vue, client/src/components/controls/Timeline.vue, client/src/views/TrackViewer/ControlsContainer.vue
Track Typename fix and some other minor issues I'm trying to tie together into this PR.
Fixes #229 - Added in a watcher to the Type Name for the TrackItem so it can update properly when changed externally
Fixes #203 - Fixed issue where it now scrolls to the proper item.  During the process I noticed that there were issues with the current frame indicator going over the top of the scrollbar and the scrollbar triggering frame changes as well.  I've updated to add a margin around the Detection/Event viewers so that way we can have scroll bars.  This also has the benefit of cleaning up the Numbers for the Detection view.
Want to add to this:
Fixes #235 - Changed the button into two independent buttons with a toggle.  You can toggle between the two and then if both are off it will hide the …
=> Track typename fix

server/viame_server/serializers/models.py
Was getting errors when testing out other files types that didn't contain polygons.  I believe this is the fix to the issue I was seeing.
=> Make polygon attribute optional

client/src/components/RunPipelineMenu.vue, client/src/lib/api/viame.service.ts, client/src/utils.ts, client/src/views/Home.vue
Inside a VIAME folder (marked for annotation) 
* disable selection of rows.
* Show "download" and "run pipeline" buttons, same as if we were in the parent folder and had selected this folder.
This should make it more clear that there's something "special" about this folder.
fixes #226
=> Change display inside VIAME folder

client/src/components/layers/AnnotationLayer.ts, client/src/components/layers/EditAnnotationLayer.ts, client/src/lib/track.ts, client/src/use/useModeManager.ts, client/src/utils.ts, client/src/views/TrackViewer/Layers.vue, server/viame_server/serializers/models.py, server/viame_server/viame_detection.py
This turned out to be a little more involved than I expected.  Had a long conversation with Bryon about approach.
Afterward, I realized that the data schema Bryon and I arrived at was pretty much exactly the same as a `GeoJSON.FeatureCollection` so instead of writing transforms in and out of GeoJSON, I figured we might as well just use that.
metadata can be kept in `feature.properties`
FYI @AlmightyYakob this needs to be resolved before the next deployment otherwise we'll have a gross data inconsistency issue and will have to write a very not fun migration.
fixes #281
=> Polygon data fix

server/viame_server/viame_detection.py
Changes the video file endpoint to the `/file` endpoint.  This endpoint properly supports streaming of files using the correct range headers.  This should fix the issue where it takes an insanely long time to load and playback large videos.  The previous version would try to download the entire file up to that one location in the space.
Let me know if there is a better way or pattern to do this.
Fixes #273 
Fixes the core of what we can reproduce for #171
=> Streaming Video Fix

docker/ansible/.vars.example.yml, docker/ansible/README.md, docker/ansible/deploy.yml, docker/girder.Dockerfile, docker/girder_worker.Dockerfile
This PR fixes several things with the deployment:
- Hopefully fixes the girder build issues by using virtual envs (haven't run into the problem testing it myself, but it's sometimes hard to induce)
- Changes the behavior of the deploy script to keep the service up while building, so that downtime is restricted to just the time it takes to restart the docker-compose service (and if there are no changes, there is no downtime)
- Pulls down the latest viame docker image (if there is one) before each build
- Add `project_directory` variable for easier development
=> Fix deployment and ensure uptime

README.md
Intended to be eye-catching and show off a little more of what's been done over the last few months.
Link to diff: https://github.com/VIAME/VIAME-Web/pull/296/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
I don't want to confuse the messaging about what this tool is, but because these features were developed with general-purpose annotation in mind, it might make sense to showcase that?
In any case, I'd like to show an example of "video" type annotation with bounding boxes and more polygon-type annotation of a single still.
=> Add more interesting imagery

client/app/views/TrackViewer/Viewer.vue
Don't know how I missed this but there was a minor typo in the handler for the feature change preventing it from functioning.  This should fix it, and it might be something we want to manually update the server with.  Looks like it isn't functioning on viame.kitware.com
=> Minor typo fix for Head/Tails support

server/tests/test_deserialize_viame_csv.py, server/viame_server/serializers/viame.py
When trying to import a new dataset, I was running into the following error when loading detections
```
Traceback (most recent call last):
File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 629, in endpointDecorator
val = fun(self, path, params)
File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 1190, in GET
return self.handleRoute('GET', path, params)
File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 946, in handleRoute
val = handler(**kwargs)
File "/opt/venv/lib/python3.7/site-packages/girder/api/access.py", line 57, in wrapped
return fun(*args, **kwargs)
File "/opt/venv/lib/python3.7/site-packages/girder/api/describe.py", line 679, in wrapped
return fun(*args, **kwargs)
File …
```
=> Fix out of bounds error on CSV rows with even number of columns and length >= 10

server/setup.py, server/tests/test_deserialize_viame_csv.py, server/viame_server/serializers/meva.py, server/viame_server/serializers/models.py, server/viame_server/serializers/viame.py, server/viame_server/viame_detection.py
This has been broken for a while, I'm not sure how nobody noticed.  This is a bug I caused.
```
girder_1         | ERROR:500 Error
girder_1         | Traceback (most recent call last):
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 629, in endpointDecorator
girder_1         |     val = fun(self, path, params)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 1208, in PUT
girder_1         |     return self.handleRoute('PUT', path, params)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/rest.py", line 946, in handleRoute
girder_1         |     val = handler(**kwargs)
girder_1         |   File "/opt/venv/lib/python3.7/site-packages/girder/api/access.py", line 57, in wrapped …
```
=> [Critical bugfix] Migrate to pydantic

server/viame_server/serializers/viame.py
If there are more annotations than filenames, don't throw a 500 out of range, just ignore it.
=> Allow annotations > filenames to not error

client/app/components/CreationMode.vue, client/app/use/useModeManager.ts
If you created a detection while track.interpolate was true, the detection would become a "Track" with interpolate=true.
There was also unnecessary complexity with newTrackMode and newDetectionMode: only a single state variable + `newTrackSettings.mode` was necessary to know.
Now, you can even change from track to detection while you're in the middle of creation (between track create and bounding box draw).
I consider this a critical fix, because for the demo, if I'm trying to explain the difference between detection and track, it's confusing to have detections acting like tracks in an unintended way.
=> [BUG] fix feature.interpolate=true getting set for new detections, simplify logic. 

client/.env.production, client/app/main.ts, client/package.json, client/src/layers/EditAnnotationLayer.ts, client/yarn.lock
Add sentry integration in production.
Note that `docker-compose up` results in a production build, so any errors in a local docker compose stack will get pushed to sentry.  I don't really care that much, but it might be a problem later.
Also, if anyone tries to run this stack on their own, they'll ship their errors to our sentry collection.  That may or may not actually be preferable.  Punt for now.
I'd like @AlmightyYakob to review this because I think he has used sentry a lot more than me.
=> Add sentry integration in prod

.env, docker/docker-compose.dev.yml, docker/docker-compose.yml, docker/girder_worker.Dockerfile, docker/provision/girder_worker_entrypoint.sh, server/setup.py, server/viame_server/viame.py, server/viame_tasks/tasks.py
Fixes #60.
This is a first pass at a system/configuration for limiting the amount of training/pipeline jobs we're running at once. Notable changes include:
* The `docker-compose.yml` file now uses 3 girder workers instead of just 1.
* One for running pipelines
* One for running training
* One for running miscellaneous tasks (image/video conversion, etc.). Any tasks dispatched with a normal use of `task.delay` will be run by this worker. This worker behaves in the same manner as the original worker, prior to this change.
* `run_pipeline` and `run_training` are now called through `.apply_async` instead of `.delay`. This allows for the specification of which queue it should go to.
* Addition and use of `girder_worker_entrypoint.sh`
* Addition and use of environment variables for specifying …
=> Rudimentary worker management/limiting

server/setup.py
This fixes the failing builds we've been seeing recently, caused by a bug I've documented [here](https://github.com/girder/girder_worker/issues/369). I've tested this locally and it seems to work without issue.
=> Update girder_worker to fix failing builds

client/src/track.spec.ts, client/src/track.ts
Better error handling for track contstructor.  If you need to construct a new track initialized with features, use `fromJson()`, not `new Track()`.   See the new test case for an explanation.
``` typescript
const features = [
{ frame: 1, bounds: [1, 2, 3, 4] as RectBounds, keyframe: true },
];
new Track(1, {
meta: {},
begin: 1,
end: 1,
features: features,
confidencePairs: [['foo', 1]],
});
```
``` typescript
const itrack: TrackData = {
attributes: {},
begin: 0,
end: 100,
confidencePairs: [
['foo', 1],
['bar', 0.9],
],
features: [
{
frame: 0,
bounds: [1, 2, 3, 4],
head: [1, 2],
},
],
meta: {},
trackId: 1,
};
const t = Track.fromJSON(itrack);
```
=> Smoke test feature array in constructor

client/app/components/DeleteControls.vue, client/app/components/EditorMenu.vue, client/app/recipes/headtail.ts, client/app/recipes/polygonbase.ts, client/app/use/useModeManager.ts, client/app/views/TrackViewer/ControlsContainer.vue, client/app/views/TrackViewer/Sidebar.vue, client/app/views/TrackViewer/Viewer.vue, client/src/components/LayerManager.vue, client/src/components/TrackItem.vue, client/src/components/TrackList.vue, client/src/components/index.ts, client/src/layers/AnnotationLayers/LineLayer.ts, client/src/layers/AnnotationLayers/PolygonLayer.ts, client/src/layers/AnnotationLayers/RectangleLayer.ts, client/src/layers/BaseLayer.ts, client/src/layers/EditAnnotationLayer.ts, client/src/layers/LayerTypes.ts, client/src/layers/TextLayer.ts, client/src/layers/index.ts, client/src/track.spec.ts, client/src/track.ts, client/src/use/useEventChart.ts, client/src/use/useLineChart.ts, client/src/use/useTrackFilters.ts, client/src/use/useTrackSelectionControls.spec.ts, client/src/use/useTrackSelectionControls.ts, client/src/use/useTrackStore.spec.ts, client/src/use/useTrackStore.ts, client/src/utils.spec.ts
Removes `vue-media-annotator` alias from the library portion of the app. Keep using it in the app part.
Blocked on #361 
fixes #304
=> Remove use of alias inside library

docker/girder_data/.gitignore
`girder_data` folder is mounted with docker compose, this will keep the directory checked in.
=> Keep girder_data folder alive

client/src/use/useTrackStore.ts
The function handles `null` anyway, so this shouldn't change anything, but it would allow for a well-typed default case if no track is selected. Something I found myself wanting on MPF.
=> Add `null` type for `trackId` in `removeTrack`

server/viame_tasks/tasks.py, server/viame_tasks/utils.py
This was due to an error in our use of `subprocess`, and the fact that using `subprocess.PIPE` to capture `stdout`/`stderr` can lead to hanging processes if there's enough output. [This](https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/) article describes the problem well. This changes all of our calls to `Popen` to instead use temporary files to capture this output. I may try to refine this to make it less work on the caller of `read_and_close_process_outputs`, but I think it would be fine to merge as is.
I've tested this on a server with a GPU to confirm it stops the SVM training from hanging.
=> Fix process hanging when training with SVM config

client/app/use/useModeManager.ts, client/app/views/TrackViewer/Sidebar.vue, client/app/views/TrackViewer/Viewer.vue, client/package.json, client/src/components/LayerManager.vue, client/src/components/TrackItem.vue, client/src/components/TrackList.vue, client/src/components/TypeList.vue, client/src/provides.ts, client/src/use/useStyling.ts, client/src/use/useTrackFilters.ts
This is the logical sibling of my provides PR to circumvent the type loss happening in emitters.
This has a certain elegance to it: the ability to globally use a collection of state and handlers without having to prescribe a specific implementation like Vuex requires.
Downstream retains full control such that it can maintain additional state and modify behaviors based on that hidden state, but the interface is fixed (which it was all along, there just wasn't a formalization).
I haven't tested this too thoroughly, but I'm happy with the style.
I'm considering implementing a sort of dummy handler for use cases like Jake where only parts will be used.  Basically an abstract base class.
=> Use provide.handler instead of emit

client/app/components/RunTrainingMenu.vue, docker/ansible/viame-deploy.timer, docker/docker-compose.yml, server/viame_tasks/tasks.py
~~Currently, these jobs are simply deleted when the server is spun up. Ideally, these jobs would be restarted, but so far attempts to do so result in new jobs remaining in an inactive state. I'd like to complete this task fully, but for now I think it's good to have this in here.~~ I've also added a warning to the client, so that users know that their training job could be killed if it's still running when the server is updated.
I've taken the advice of @subdavis, now if the server is restarted, existing running tasks will be restarted.
=> Remove lingering running/cancelling jobs on girder start

.github/workflows/blank.yml, .github/workflows/release.yml, client/README.md, client/package.json
This will allow us to publish `vue-media-annotator` by creating a release through github UI.
You must be sure that the release tag is `X.X.X` and greater than the last version released.
=> Add github action for publish workflow

client/src/components/annotators/ImageAnnotator.vue, client/viame-web-common/components/Viewer.vue
Fixes #420
FPS fix - the FPS was automatically a number so it was failing in the computed property to return the proper value and was defaulting everything to 10.
Image Cache fix - The original image caching would cache 6 seconds of data initially for image sequences.  This works for standard images but not for 16MB+ images.  It's trying to load all 7 images (at 1 frame per second) without any order priority so the first image may be the last to load.  I defaulted to loading the initial image first, then followed by caching so you can move through at least some images quickly and the system isn't sitting there doing nothing while you gawk at the first image.
Please test and make sure I didn't completely mess something up.
=> Fixes FPS issue and image caching

.github/workflows/blank.yml
Upgrade to node 14.15 LTS because 10 is ancient.
**You should probably upgrade your local NodeJS version to 14 or 15 too.**
=> Upgrade CI tests to run in Node 14.15 LTS

client/README.md, client/checkbuild.sh, client/package.json
I get a little impatient waiting for CI to run 10 minutes worth of checks, so this script will perform the same steps as CI in parallel.  It takes roughly 90 seconds on my machine.
That way you can be confident that your commit is functional before you push and waste less time fixing minor CI errors.
I don't want to add this as a commit hook.  It takes too long, and often I need to create a transient broken commit.
=> Add checkbuild.sh

client/src/components/annotators/VideoAnnotator.vue
`<video-annotator :video-player-attributes="{ muted: true, loop: true }" />`
You can absolutely footgun with this.  But I wanted to expose all possible configuration rather than having explicit props for everything.
I put it below `src, preload` to allow hacking on those, but above `onloadMetadata` because that would be unreasonable to try to hack.
=> Allow setting of arbitrary attributes on video player

server/viame_server/serializers/models.py
I really don't know how we never noticed this.
Who wrote this stupid code anyway.
=> [Bugfix] inverse interpolation

client/package.json, client/src/provides.ts, client/viame-web-common/components/Viewer.vue
**This is a breaking change, and will upgrade to `1.1.0`.**
* Change arguments to `provideAnnotator` to accept an object, because the positional args were getting out of hand.
* Add methods to generate dummy state and a dummy handler compliant with the interface so that they can be easily overridden by downstream apps with much simpler needs.
``` typescript
provideAnnotator(
{ ...dummyState(), tracks: myTracks },
dummyHandler(() => {}),
);
```
@AlmightyYakob and I have talked about this change
=> Add dummy generators

client/platform/web-girder/views/ViewerLoader.vue, client/src/components/annotators/annotator.js, client/src/layers/EditAnnotationLayer.ts, client/viame-web-common/components/RunPipelineMenu.vue, client/viame-web-common/components/Viewer.vue
Just some really minor UI fixes to reduce the backlog
- Fixed the `annotator.js` references to `geo_actiton_select` and the owner
- Fixes #409 - changes the text and allows the user to prevent themselves from exiting the current view
- Fixes #278 - just a text change which shouldn't be used as a key anywhere else
- Fixes #388 - remove the pencil icon while in editing mode, left the others so you know what type you are drawing
=> Minor ui fixes

client/viame-web-common/components/AttributesPanel.vue, client/viame-web-common/components/Sidebar.vue
See actual changes in inline comments.
All this really does is 
*  aligns the headers, fixes an alignment issue in icon pencil buttons
* changes the background color because all the white lines are just noise to my eyes.
* makes the headers more dense, vertical space is precious.
Also ran autoformatting.
=> Some suggestions

client/src/provides.ts, client/src/use/useTrackStore.spec.ts, client/src/use/useTrackStore.ts, client/viame-web-common/components/AttributesSubsection.vue, client/viame-web-common/components/TrackDetailsPanel.vue, client/viame-web-common/components/Viewer.vue, client/viame-web-common/use/useModeManager.ts
I didn't mean for you to add `getTrack` to the provided interface.  I don't know if you did that because you wanted to or you thought it's what I wanted.
* This would be a departure from the style of provided state.  In your change, getTrack is a partial function application where trackMap is already in the closure.  We don't have any other state like that, so it might be good to do it this way just for consistency.  
* More importantly, though, the point of `getTrack` is to to throw an error if the requested track is missing, which is useful in the common case where missing track would need to be a runtime error (i.e. selectedTrackId should always be in TrackMap).  This is how it worked in your change, but the type of `GetTrackType` included `undefined` which somewhat defeated the …
=> change getTrack

.gitattributes, client/src/components/annotators/VideoAnnotator.vue
Fixes #447 
the gitattributes change is to prevent enforcing newline on the new gifs that merged from #448
=> Add seek(0)

client/src/components/annotators/ImageAnnotator.vue, client/src/components/annotators/annotator.js
fixes #55 
For multi-resolution image sequences already in the system, this will cause all detentions to become mis-aligned.
I haven't tested this extensively yet.
=> Multiresolution image sequence support

client/package.json, client/src/components/LayerManager.vue, client/src/layers/TextLayer.ts
=> Format text custom function

client/src/components/controls/Controls.vue, client/viame-web-common/components/ControlsContainer.vue, client/viame-web-common/components/Viewer.vue
This looks like a lot of changes, but it's really just a couple indentation changes.  I removed the `v-toolbar` and `v-container` wrappers in the toolbar because they provided no value, replaced with a fluid-height `v-card` so that text wrapping looked correct at narrow widths.
Had to move controls into the `timeline-wrapper` so that `frame` prop from annotator slot could be used.
Got rid of `annotatorType` derived property because we already have an explicit `meta.type` associated with the dataset.  
I put it in the time control bar because that's where it made most sense to me.  It's tightly coupled to time/frame controls, so having it in the header seemed like a violation of locality.  Also, I haven't done this yet, but on videos the filename text would be replaced with a timestamp, …
=> Add current frame image filename to display for image-sequence

server/viame_server/serializers/viame.py, server/viame_server/training.py, server/viame_server/viame.py, server/viame_server/viame_detection.py, server/viame_tasks/tasks.py, server/viame_tasks/utils.py
Not the best way to solve the issue but the least intrusive way for the time being.
Pipeline Running Updates:
- `image-sequence` for training will now filter out .json files
- `video` type will now load the folder filter out any non compatible video files and then look for the video file which doesn't have the codec meta tag on it.  I would like to share the `validMediaFiles` with the constants folder or maybe do this filtering before calling the task, I just didn't want to go with too big of a change right now with just getting video training to work.
CSV Metadata Update:
- Added in the writing of the metadata to the header.  Right not it only writes the fps value for the training and other items to user.  More stuff can be added in the future, just trying to keep it fairly simple right …
=> Video Pipeline/Training Support

docker/docker-compose.yml
Because the volume was being populated by 3 containers, there's a race condition for whichever loads first, and others will try to "copy" their data over to the host mount and fail.
Only expose the volume to girder from a single worker.   It doesn't matter which one, since they all have the pipelines directory internally.
=> Only source pipeline volume from one place

client/README.md, client/checkbuild.sh, client/package.json, client/platform/desktop/backend/ipcService.ts, client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/linux.ts, client/platform/desktop/backend/native/windows.ts, client/platform/desktop/backend/serializers/cli.ts, client/platform/desktop/backend/serializers/viame.ts, client/platform/desktop/backend/server.ts, client/platform/desktop/frontend/store/index.ts, client/src/track.spec.ts, client/src/track.ts, client/src/use/useTrackStore.spec.ts, client/tsconfig.cli.json, client/tsconfig.json, client/yarn.lock, server/viame_server/serializers/viame.py
Includes non-trivial build configuration changes.  See package.json, tsconfig, and README for explanation.
The change of `import Track from 'viame-web-common/track'` in the parser (in order to use Track.trackExceedsThreshold) unleashed a lot of hidden trouble.  I've understood some new things about the typescript compiler and simplified the tsconfig, and was also able to drop `ts-node` dependency.
`yarn watch:cli` will autorebuild the cli, which you can run with `yarn divecli`.
Required by #493 #509 #487
=> Desktop CSV Serializer

client/src/components/annotators/VideoAnnotator.vue
Lead to bugs mostly in useModeManager where mediaController was undefined.
=> [Bug] [Critical] mediaAnnotator bug

.github/workflows/release.yml
Allows release to succeed.  Can consider a more suitable fix later.
=> Disable unit testing on windows for now

.github/workflows/release.yml
The product name was changed, but the upload glob was missed.
=> New asset name

client/platform/desktop/backend/native/viame.ts
Simple command line to enable support for training in windows by eliminating some incompatibility with logging.  It reduces advance displaying of the console commands.  I don't think this matters because we are using just standard txt for displaying and output on desktop. 
I tested on Linux and there were no adverse effects with adding this command line in here.
This was tested on windows using some modified python to fix an unrelated error that should be released soon (I would think v0.13.2).
=> windows support for training

client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/frontend/components/MultiTrainingMenu.vue
Pipeline outputs follow the way the web is done with a `{type}.pipe` file and a .zip file that are moved into a folder in the DIVE_Pipelines.  This folder is spread onto the pipeline object with the category of 'trained' when the pipeline list is requested.
- After a pipeline is complete it will check the job folder for a category_models folder and then check the contents for the `[type].pipe` file.  Then it will move that into the DIVE_Pipelines directory.
- Modified the exit function for training to include some errors if it can't find the .pipe file or directory.  I wish I knew a bit more about what is expected in there for the different training configurations.
Question:
- Let me know if you think it should be a JSON file indexed with trained pipeline folder instead of utilizing the …
=> Desktop Using Trained Pipelines

.github/workflows/release.yml, docs/Dive-Desktop.md, docs/index.md
Automated docs deploy on release.
Reorder homepage to de-emphasize definitions (Matt asked for this)
Add info about download to OS mappings.
Fixes #562
=> Update tdocs, add to release

client/src/components/LayerManager.vue, client/src/layers/EditAnnotationLayer.ts
More explicitly determines what changes will cause disabling the current editing process.  Changes to the track type or other values shouldn't cause the in process annotation to disable and reset.   Changes to the editType, selectedTrack or selectedKey will cause the editAnnotationLayer to disable and switch to a different mode.
I'm using the existing changeData stuff for line creation to skip updates when data not relevant to the current editing Type (line,rectnagle, poly) or selectedKey isn't changed.  So if track types are changed it won't kick it out of editing mode.
I found another issue in here related to continuous head/tail mode that has to do with rectangleLayer selecting the previously created mode on mouse release right after creation causing the older trackId to be reselected …
=> Creation mode switching bugfix

client/platform/desktop/frontend/components/Recent.vue
Sorry this happened enough times I just needed to adjust it.
Mainly did it because of the phantom link opening when I was clicking on Dive to achieve window focus.  The root of those links were in a column so they were interpreted as a row that went across the full width of the app.  About 6 different times I accidentally opened the Help/Viametoolkit.org or another link clicking in the blank space between the actual link text and the buttons on the right
=> Phantom desktop clicking opening links

client/src/layers/TextLayer.ts
There was still an off-by-1 issue with this function.  If you provided `additionalNum` > `confidencePairs.length - 1` you'd end up with a height miscalculation for lines n>1
However, I think the function was generally more complicated than it needed to be.  Here's a version with a simple `maxLines` arg that will show up to `maxLines` rows.  You don't have to think about any off-by-one conditions because there's just  a single loop and no special external conditions or break condition.
=> Confidence sort brandon

client/src/use/useAttributes.ts, client/src/use/useTrackStore.ts
Just updating the types in `useAttributes` and `useStyling`  for `markChangesPending` to be compatible with the newer style, it just had extraneous information before.  We could export the markChangesPending type and use that, but this forces  each `use` item to using the data and structure specifically associated with it.
=> markChangesPending update for typeGuards

client/dive-common/use/useSave.ts, client/src/track.ts, client/src/use/useAttributes.ts, client/src/use/useTrackStore.ts
Bryon, I saw your comment and it looked like this might be a good use of type guards.
I haven't tested this, I'm not even 100% sure this is a good solution.  I'm more just interested in if you think this is better style or provides more safety.
Risks to this change: 
* Updating the interface but forgetting to update the guard.  They're defined next to each other, so hopefully this is mitigated.
* Doesn't place enough trust in the type system. (similar to above)
* Too generic, hurts readability.
LMK what you think.
=> Try type gurads

client/dive-common/use/useModeManager.ts, client/src/components/LayerManager.vue, client/src/components/TrackItem.vue, client/src/layers/EditAnnotationLayer.ts, client/src/layers/TextLayer.ts, client/src/track.ts
Several issues.  
* [minor] Reverted `checkCreationIncomplete` because I still don't know what it does (#475)
* [important] Fixed issue where, during bbox creation, in editing mode, if you move away a frame then come back, you'd be kicked out of editing mode.
* [important] Fixed issue where newly created bounding boxes didn't go directly to editing mode 
* [minor] Fixed issue where, during continuous creation, moving between annotation types (rect, poly, back to rect) caused you to get kicked out of continuous mode.
* [important] fixed text styling issue where all colors changed when track entered editing mode (rather than just the text for a single track)
Noticed mostly during demo recording.  **Still no fix for continuous head/tail creation**
=> Fix annotator creation mode bugs

client/platform/desktop/backend/native/linux.ts, client/platform/desktop/backend/native/windows.ts, server/dive_tasks/tasks.py
Note that this fixes one of the only failures I could find related to video where the sample data had not been removed.  This may not  be the cause of every transcoding issue.
fixes #353
=> Transcode audio to AAC to prevent incompatible container formats

client/src/components/TypeList.vue, client/src/provides.ts, client/src/use/useStyling.ts, server/dive_server/constants.py, server/dive_server/serializers/models.py, server/dive_server/viame.py
I've been trying to move toward pydantic for strict valudation of incoming models, and this looked like a good place to choose pydantic over a hand-rolled version.  
`extra = 'forbid'` results in the same exclusions as `metadataReserved`, but there's a difference in behavior with expunged.
I don't really understand the value of expunged, and I think it'd be better to throw an error if the payload isn't identical to what the server expects.  The only risk I could come up with was that save failure would cause the user to lose a bunch of hard work (as the result of a client bug), but track save will still succeed even if meta save fails.  
The benefit here of course is less code and deep schema enforcement (rather than just based on key).
What do you think?  Are there considerations I …
=> Use Pydantic for validation

client/package.json, client/tsconfig.json, client/vue.config.js
* The tsconfig comment will cause an error during release.  It's not part of the build step.
* At some point we had to release differnt versions of electron and vue-media-annotator, but now they're on track and it's easier to just release both under the same version number.  It's not like we have enough users that strict semver matters
=> Release 1.4.4

docker/README.md, docker/docker-compose.prod.yml
* Nvidia docker2 is not deprecated, it is the current supported nvidia docker runtime.
* GPU support for compose has now landed.  I didn't upgrade the actual compose version because if-it-aint-broke, but if we wanted to use more fine-grained GPU device selection, we could now.
* Explicitly mention that the docker install is linux-only, and point to alternatives.
=> Docker nvidia docs out of date

client/dive-common/components/ImportButton.vue, client/platform/web-girder/views/Home.vue, client/platform/web-girder/views/Upload.vue, client/platform/web-girder/views/UploadGirder.vue
So I rearranged a lot here, but only because
1) I think what you did is already a big improvement on what we had before and
2) I think this upload is really important to get right.  
I wanted to address a few issues
* Also removed a bit of dead code, like the CSS that used to take care of the dropzone we don't have anymore.
* Migrated some complexity from GirderUpload to Upload
* Fixed issue where "Abort" button didn't do anything
* Removed all use of `v-list*` elements because you replaced them with cards and they weren't doing anything.
There appear to be some unhandled failure conditions I'm still working on.
* When uploading multiple datasets where one will fail (name conflict) the whole thing fails in a weird way
* Failures in postprocessing fails silently.
=> Adjust templates

docker/README.md, docker/provision/girder_worker_entrypoint.sh, server/dive_tasks/celeryconfig.py, server/dive_tasks/tasks.py
* Turns out heartbeat was useful. I'm learning lots of stuff about celery.  I was trying to test the behavior more robustly by running a worker and turning my VPN on/off, pulling out my ethernet cable, etc.  Without the heartbeat, the rabbit server doesn't know when a connection has been lost.  Mailbox reservation gets stuck and messages start to flow into a mailbox for a worker that is no longer listening.  With heartbeat, the mailbox will eventually be cleared and the job with get rescheduled on another worker.
* Add `KWIVER_DEFAULT_LOG_LEVEL`.  Some processes don't respect this variable, but that's not dive's concern.
* I've experimentally found that the timeout error handling works well, so I've dropped the timeout to a more reasonable value.
Our cancellation error handling means that …
=> Minor worker fixes

server/dive_tasks/utils.py
This would have fixed https://viame.kitware.com/girder/#job/60a27a583753b80a81e13e55
I'm not sure if this is a fluke, a band-aid fix, or caused by network unreliability inside KHQ.
=> Catch connection reset exception

client/dive-common/components/RunPipelineMenu.vue, client/dive-common/components/RunTrainingMenu.vue, client/platform/web-girder/api/summary.service.ts, client/platform/web-girder/views/Clone.vue, client/platform/web-girder/views/Export.vue, client/platform/web-girder/views/Home.vue, server/dive_server/serializers/viame.py, server/dive_server/viame_detection.py, server/dive_server/viame_summary.py, server/dive_tasks/summary.py, server/dive_utils/models.py
Something to note: In order to make this fast, the actual detections (features) are not parsed, and instead the track bounds are used.  That means that a track that spans 10 frames but that has no detection on a given frame will be counted in the summary for that frame.  I believe this is correct from a stasticical perspective: the target is occluded, but exists in the frame.
If this is an incorrect way to count, the summary generator will need to be moved into a worker process and this will add some complexity.
I want to make the summary button it's own dialog with other report types, but this was the quick version.  I added some icons to the button to indicate which ones had "submenus" but I could revert this if you want.  Until now, all those buttons were "safe" -- they didn't do …
=> Calculate Max N for all classes for multiple datasets

server/dive_server/training.py, server/dive_server/utils.py, server/dive_server/viame.py, server/dive_server/viame_detection.py
Fixes a somewhat nuanced bug with training with clones.
Biggest issue was `new_file = File().findOne({"name": filename}) or File().createFile(`
* Obviously identifying files to generate groundtruth by name is a real bad plan.  However, since `ensure_csv_detections_file()` and `_generate_detections()` were almost identical functions and that code is complicated enough that copy/paste is a bad idea, I refactored into `get_annotation_csv_generator()`.  There were bugs in both variants that needed to be fixed.
* This fixes a related bug where the generator fails to call clone root to populate the list of input images, causing the CSV to be missing that column.
* This fixes an unrelated bug where advanced image ordering was not applied to the CSV export image listing.
This has been a lesson in …
=> Dedupe detection generation code, fix clone training bug

client/src/components/TrackList.vue, client/src/components/TypeList.vue
fixes #645 
Displays counter in parentheses next to selected type. Literal count of all tracks in track list grouped by type. When the type is unchecked, the counter disappears. Counter updates automatically as the confidence filter slider is changed. 
Still need some tests on performance and efficiency.
=> Added population counters for selected types

client/src/use/useTrackStore.ts, testutils/scripts/generateLargeDataset.py
Test script is used to create large datasets for testing.  Just run the `python generateLargeDataset.py -h` to get he input arguments.  It may not be perfect at this time so please update if you see any errors.
The call- stack fix is related to:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max#examples
Look at the spread/apply example
Then look at:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#using_apply_and_built-in_functions
Specifically about the limitations with length of arrays being applied, although it seems like the default number increased at some point.
Note:  Using the generateLargeDataset.py with `python3 generateLargeDataset.py --images 100 --types 2000  --tracks 180000` will produce a …
=> Fix Call Stack Error and add test script

server/dive_server/utils.py, server/dive_server/viame.py
fixes #802 
- Added check at the end of post process to ensure that if no detection file is found it will automatically create one
- Added the same check to the clone data, so that if there are existing datasets without a base detection on clone it will create an empty track file as well.
=> PostProcess detection creation

client/dive-common/components/UserGuideDialog.vue, client/dive-common/components/Viewer.vue, client/platform/desktop/backend/server.ts, client/src/components/TrackItem.vue, client/src/components/TrackList.vue, client/src/track.spec.ts, client/src/track.ts, docs/Mouse-Keyboard-Shortcuts.md
Some minor bugfixes
Fixes #762 - disabling button while save is in progress
Fixes #765 - expressJS setting of JSON limit to 250MB from the default of 100KB
Fixes #728 :  
- Added in 'K' for toggle keyframe as well as updated the shortcuts in the help for split/merge/keyframe.
- Modified v-mousetrap to hidden div only visible when the item is selected.  Before the shift+enter focus call was added and called on all visible items in the virtual scroll list.  This will limit it to only the selected one having keyboard shortcuts applied.
- Keyframes should be added and removed while in edit mode by pressing K
- Added in toggle interpolation shortcut "I"
- "Enter" no longer went to first frame, modified for "Home" or "End" going to the first/last frame of the currently selected track
- Updated …
=> Grouped minor fixes

client/src/components/annotators/useMediaController.ts
Fixes #808 
Quick fix for the resizeObserver Error.  My understanding is that this is an error in chrome/firefox that isn't typically logged but can be shown if you subscribe to all errors on the window object : `window.onerror = (e) => console.log(e)` that should show it.
It looks like it is a true infinite call error that the browser handles gracefully so that is why it isn't shown in console.log by default.  The act of resizing the geoJS area during a resize event creates I think a cascading call to resize which the browser interprets and handles.  Throwing a `requestAnimationFrame` around it will delay the setting and hopefully prevent recursive updates.
You can  test it by using the console.log for the window.onerror and loading data and resizing the window while monitoring the …
=> Quick Fix for ResizeObserver Error

server/dive_server/viame.py, server/dive_tasks/manager.py, server/dive_tasks/tasks.py, server/setup.py, server/tox.ini
monkey-patch the girder worker util manager _flush() function to drop logs on 5XX.
fixes #809
=> Truncate logs on fluxh 5XX error

client/dive-common/components/Viewer.vue
This is a really obvious intermediary fix for issues where the page locks up during data load that we should have added months ago.
* Add a percentage progress bar to show how much of the dataset is loaded
* Take 500ms breaks every 4000 track loads to yeild CPU time to other scheduled tasks on the page during load time.  This will prevent the browser from trying to kill the page for "not responding" as can happen with really large amounts of data.  For absurdly large amounts of data, it also provides much better user confidence that something is happening.  
I picked the batch and sleep numbers somewhat arbitrarily because the vuetify progress spinner is kinda buggy and runs its transitions in JS land rather than in CSS.   It was implemented such that the transitions stack and can get …
=> Take breaks when loading large amounts of data

client/platform/desktop/backend/native/migrations.ts, client/platform/desktop/frontend/components/ViewerLoader.vue, client/platform/desktop/frontend/store/dataset.ts
- Updated the viewer loader so that it will default to standard data instead of an undefined value.
- Updated the `upgrade` function for `meta.json` so it will properly set the subType if not available.
=> Fixing loading within 1.4.10

client/package.json
Because 1.4.10 had already gone out to NPM, it can't be re-released.
Since this contains significant new features and some schema changes, I went for a minor version bump.
=> Release 1.5.0

client/package.json, server/setup.py
Updated `server/setup.py` to remove `include_package_data=True`. Although, it is used by other projects in girder, since this project does not use `MANIFEST.in` file, this option should not be used. _This option does not matter since it is being deployed using docker, but if the Python project were to ever be published to pypa using bdist, this would cause issues_
As discussed, changed the `version` in `server/setup.py` to 1.0.0 since this will not be updated and should be kept at a consistent number. 
Fixed the `packages=find_packages` in `server/setup.py` to include the correct directory names.
Changed the license field in `server/setup.py` to the correct Apache license name and updated the classifiers in `server/setup.py` to include all valid Python versions. This is what is used by …
=> Updated server/setup.py and client/package.json

client/src/components/TrackItem.vue, client/src/track.spec.ts, client/src/track.ts
Fixes #758 
- Prevents the user from toggling off the keyframe when there is only a single detection available
- Does this by disabling the keyframe button and the keyframe toggle keyboard shortcut
- This is done client side because we don't want a user assigning 
- Added to the `track.toggleKeyframe` an error thrown if it manages to togglekeyframe and the begin === end frame and the current frame is equal to one of them.
- Added some tests to make sure the error is properly functioning when toggling a keyframe on the only feature
Question:
- To prevent ghost tracks should there be an error thrown on `deleteFeature` if you are trying to delete the only feature in a track?
=> fixing toggleKeyframe 500 error

server/dive_utils/models.py
Silly mistake.
Pydantic's default mode is to `extra.ignore`, or to drop extra unknown fields.  Because we validate on save, the flick wasn't getting saved.
This allows the flick to be saved, but is not otherwise used. 
fixes #828
=> Allow flicks to persist server-side

server/dive_server/utils.py
The coco check tries to open the file up directly which will result in this:
`{"message": "Read exceeds maximum allowed size.", "type": "girder"}`
If the file is too large.
I just switched it to use the standard `json.loads(file().download())` format instead and that seems to fix the problem.  I also did some basic testing to ensure that the coco loader still works properly.
=> Large JSON file uploading fix

.github/workflows/blank.yml
15 minutes is a ridiculous CI run time.  This reduces CI time to roughly 6m30s.  Electron alone takes 5m30s so I think this is about the best that can be done.
* Adds matrix to parallel build web, lib, and electron
* Adds yarn cache layer, though the speedup here is really negligable because install drops from 70 to 30 seconds but the cache hydration takes 30-40
Probably a 2x overall speedup.
=> Parallel CI for client

client/dive-common/apispec.ts, client/dive-common/components/RunTrainingMenu.vue, client/platform/desktop/backend/cli.ts, client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/constants.ts, client/platform/desktop/frontend/api.ts, client/platform/desktop/frontend/components/MultiTrainingMenu.vue, client/platform/web-girder/api/viame.service.ts, docs/Pipeline-Documentation.md, server/dive_server/viame.py, server/dive_tasks/tasks.py
resolves #771
Checkbox added in training menu to choose option to only train on annotated frames and ignore frames that are not annotated. This is enabled by default for both web and desktop. This checkbox is passed as an additional parameter to the kwiver call.
Web:
Desktop:
Also modified CLI to incorporate this new change by adding the `--annotatedFramesOnly` flag which is false by default.
=> Checkbox to use annotated frames only when training

client/dive-common/components/ImportAnnotations.vue, client/platform/desktop/backend/native/common.ts, client/platform/desktop/frontend/components/ImportDialog.vue, client/src/use/useTrackStore.ts
Fixes #871 
Fixes #873 
871 - upated `_importTrackFile` so that it can accept a duser defined track file.  If that track file is not included it will fall back to the default operation (This is required for stereo import of folders).  If it is included and set to null/empty it will create an empty dataset.
873 - added a disabled state and spinner to the import for longer uploads.  The previous delays were actually caused by the clearing of the tracks and not the import process itself.  If modified the clearAllTracks function to remove the objects instead of iteratively calling `removeTrack`.  This sped it up so on desktop it should be relatively quick and the longest part will be reloading the data.
=> import fix and some animation for importing

.github/workflows/release.yml
In a pickle where NPM release succeded, then windows build failed.
It's not possible to unpublish from NPM (because the release was done in CI, so the SHA is lost) so I need to allow publish to fail to let the rerun complete everything else.
=> Release to NPM last, allow it to fail

client/platform/desktop/backend/cli.ts, client/platform/desktop/backend/native/linux.ts, client/platform/desktop/backend/native/windows.ts, client/platform/desktop/frontend/components/Recent.vue, docker/girder_worker.Dockerfile, server/dive_tasks/tasks.py
Tested AV1 using this video from https://github.com/SPBTV/video_av1_samples/blob/master/spbtv_sample_bipbop_av1_960x540_25fps.mp4
Verified that browser will play av1 without transcoding, but that web and desktop are still choosing to transcode anyway because of VIAME support.
fixes #750 
fixes #855
=> AV1 Transcoding Support, CRF=22

docker/README.md, docker/docker-compose.yml
Just fixing because without traefik started you need to reference your local Docker IP and port 8080.  The previous instructions of `docker-compose up girder` would have left the server in that state.
Also noted that you won't have video import working in this mode (the worker container won't be up, so upload hangs).
=> updating GPU-less running instructions

server/dive_utils/serializers/viame.py
Fixes #840 
Just a small fix to write the header when the `track_dict` is empty.  Doubled checked the desktop/nodeJS version and it writes it each time.
=> write header for empty CSVs

server/dive_tasks/frame_alignment.py, server/dive_tasks/tasks.py, server/dive_tasks/utils.py
While reviewing on friday, I noticed there were some unhandled cancellation conditions, most notably in `check_and_fix_frame_alignment()`.  I implemented cancellation poorly to begin with such that any function call that could interrupt the function has to be checked on return (in the same way that golang error handling works) so you have to check all the way down the call stack.
This is the whole purpose of built-in error handling language features (throw early/catch late).  This gets rid of most instances of `check_canceled` so that forgetting handle the cancel somewhere won't introduce bugs.
It also replaces `self` with `task` in some functions.  Self shouldn't be the name of an argument in a function that isn't an instance method (celery tasks are a special case)
This is untested (I …
=> Fix Cancellation

client/platform/desktop/backend/native/attributeProcessor.ts, client/platform/web-girder/views/Upload.vue, client/platform/web-girder/views/UploadGirder.vue, server/dive_server/crud.py
Feel free to take what you want or reject the merge.
- The standard upload UI would fail non-gracefully when selecting an incorrect JSON file so I added a prompt and error handling to the postprocess request.
- I felt like the offending JSON file should be removed from the dataset folder if it is found to not be a compatible type.  Otherwise we have a bunch of orphaned json files sitting there on export.
- Small error throwing message on desktop-electron to make it clearer why there was a failure.  There was a failure processing attributes which could cause an error in the import.  Alternative would be to check for some basic schema in the `loadJSONTracks`, there is a TODO there for that.
=> Updates to import-failures

client/dive-common/components/ImportAnnotations.vue, client/platform/desktop/backend/native/attributeProcessor.ts, client/platform/web-girder/api/dataset.service.ts, client/platform/web-girder/api/rpc.service.ts, client/platform/web-girder/views/Upload.vue, client/platform/web-girder/views/UploadGirder.vue, server/dive_server/crud.py
fixes #903
Until now, apparently the client would let you upload whatever json you wanted and postprocess would tag it as an annotation file without checking the formatting.  Now, it's forced through a pydantic schema validation same as if you `save`.
Also fixes a bug where `api.importAnnotationFile` was not updated to use the new postprocessing endpoint.
=> Fixes #903 Import annotation error handling

server/dive_utils/models.py
Some of the customTypeStyling values in my directory have `type`
Example https://viame.kitware.com/girder/#user/5e56c7d778ed364cd0fd30a2/folder/5f3c78e0531f8b4f23542d3f
This causes a 500 error when the data loads.  Rather than forbid, we should just ignore the extra value.
Apparently from an old version of the interface: https://github.com/Kitware/dive/pull/192/files#diff-e7e29d171278c9dd2b7a6351646365c7ad7f38aabc1f0b5c5f6ec487acf95177R35-R41
=> Remove forbid on CustomStyle

docker/docker-compose.prod.yml, docker/docker-compose.yml
* The girder health check is worthless and spams the access log with 90% empty noise, making logs rather hard to look at.
* Traefik was missing restart:always, so the service doesn't come back up when the server restarts, which was an issue today.
=> Updates for docker compose

client/package.json, client/platform/desktop/frontend/components/Settings.vue, client/yarn.lock
Will require a minor version bump for consumers of `vue-media-annotator`
=> Upgrade vue, template compiler, composition api

client/dive-common/components/Sidebar.vue, client/dive-common/components/TrackSettingsPanel.vue, client/dive-common/components/TypeSettingsPanel.vue, client/dive-common/components/Viewer.vue, client/dive-common/store/settings.ts, client/dive-common/use/index.ts, client/dive-common/use/useModeManager.ts
@BryonLewis while reviewing #891 I had an idea to try something.
I think I've abused the composition function pattern in `dive-common` somewhat by representing singleton modules like settings, useSave, and modemanager as composeable when they're really just state and mutation functions.  In desktop, we have the `store/` folder for these, but there are no singleton stores in `dive-common`.
The idea is that anyone who wants to use settings can just `v-model` the imported reactive object, and a watcher inside the store persists changes into localstorage when the settings object updates.
It drops about 100 lines of code and makes settings much more straightforward to use from anywhere in the app, but I'd like to know what you think.  Are there risks to doing it this way?
=> Try settings singleton

client/platform/web-girder/App.vue, client/platform/web-girder/api/dataset.service.ts, client/platform/web-girder/router.ts, client/platform/web-girder/store/Dataset.ts, client/platform/web-girder/store/Location.ts, client/platform/web-girder/store/index.ts, client/platform/web-girder/store/types.ts, client/platform/web-girder/utils.ts, client/platform/web-girder/views/DataBrowser.vue, client/platform/web-girder/views/DataShared.vue, client/platform/web-girder/views/Home.vue, client/platform/web-girder/views/JobsTab.vue, client/platform/web-girder/views/NavigationBar.vue, client/platform/web-girder/views/ShareTab.vue, client/platform/web-girder/views/ViewerLoader.vue
This backs out some of the nonsense I added when we worked on this the first time and simplifies things a bit.
* Remove `LocationGetters` and `GettersDefinitions`, as they were providing no additional safety whatsoever.
* Move `'auxiliary'` enforcement and hydration of full location model into `route` handler.  These things should happen no matter where the location is routed from.  The current behavior relied on lifecycle of `DataBrowser` and was therefore subject to `keep-alive`.
* Tweak getLocationFromRoute such that the argument is, as the name suggests, a route.  At that point in the execution, it has not been determined that `route.params` is actially `LocationType`, so the arguments to that function resulted in an untrue type coercion.
* Remove the somewhat obscure computed …
=> Fixes for location

client/src/components/TypeEditor.vue, client/src/components/TypeList.vue
Refactor type list settings into its own component so that type settings can be invoked elsewhere.
I was already in progress before discussing #897 with bryon yesterday, and it seemed nice to finish.
Reviewer should notice no behavior changes.
=> Refactor typelist settings

server/dive_tasks/tasks.py
Simply adding the MOUSS Deep 7 to the add-ons so they are downloaded with the rest of the data.
Tested it locally with pulling the models down and then running them on sample datasets, looks like it is good.
=> Adds newest mouss add-on to the default add-on downloads.

client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/multiCamImport.ts, client/platform/desktop/constants.ts, client/platform/desktop/frontend/components/ImportDialog.vue, client/platform/desktop/frontend/components/Recent.vue
fixes #922 
Added in new Transcode option under the advanced import options.
Transcode will add the video to the `mediaConvertList` (The list that will determine if items are not web safe and should be transcoded, or transcoded for non-square pixels/ frame misalignment).
=> Adding in forcing transcode option

client/dive-common/components/Viewer.vue, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/frontend/components/Jobs.vue, client/platform/desktop/frontend/components/ViewerLoader.vue
fixes #939 
Was fixed by swapping the order of the `detectorOutput, trackOutput` in the `processOtherAnnotationFiles` to cause it to load them in sequence where if the `trackOutput` exists it is the final result.
fixes #937
Simple fix with a text error on the attribute.  Swapped `read-only-mode` to  `readonly-mode`
fixes #924 
In the `ViewerLoader.vue` placed a watcher on the jobs queue.  Will check to see if a job with which contains the same ID as the currently loaded one if it has completed successfully and if the jobType is a pipeline.  If all those conditions are met it will prompt the user telling that it is complete and if they want to reload the annotation.  Then it calls the standard reloadAnnotation function used for stereo and importing.
fixes #940 
Changed the list in the jobs …
=> Desktop Fixes

docker/.env.default, docker/docker-compose.dev.yml, docker/docker-compose.prod.yml, docker/docker-compose.workers.yml, docker/docker-compose.yml, docs/Deployment-Docker-Compose.md, docs/Deployment-Provision.md
* Compose 1.28+ supports device requests
* So we no longer need to specify a runtime
* We just have to ask for GPUs
This will require an update to the version of compose running in prod
=> Upgrade to compose 1.28, switch to device requests

client/src/components/annotators/ImageAnnotator.vue, client/src/components/annotators/VideoAnnotator.vue, server/scripts/commands_dev.py
This is a redo of #1015, since the commits from that were merged but not squashed.
=> RE: Add brightness prop and svg filter

server/dive_server/crud.py, server/dive_utils/models.py, server/tests/integration/test_dataset_download.py, server/tests/integration/test_dataset_operations.py, testutils/tracks.json
fixes #1012 
Adds new integration tests.
=> Allow upload of DIVE json.

client/src/components/LayerManager.vue, client/src/components/TrackList.vue, client/src/components/TypeEditor.vue, client/src/components/TypeList.vue, client/src/components/annotators/ImageAnnotator.vue, client/src/components/annotators/VideoAnnotator.vue, client/src/components/annotators/useMediaController.ts, client/src/layers/TextLayer.ts, client/src/use/useEventChart.ts, client/src/use/useLineChart.ts, client/src/use/useTrackSelectionControls.ts
When using `vue-media-annotator` externally, attempting to import anything from `src/layers/TextLayer.ts` (in my case the `TextData` type), the following error is thrown:
```
1:29 Cannot find module 'vue-media-annotator/use/useStyling' or its corresponding type declarations.
> 1 | import { TypeStyling } from 'vue-media-annotator/use/useStyling';
|                             ^
2 | import BaseLayer, { BaseLayerParams, LayerStyle } from './BaseLayer';
3 | import { FrameDataTrack } from './LayerTypes';
4 | 
```
I suspect this is due to the fact that in the project itself, `vue-media-annotator` is an alias to the `src` directory.
This PR just replaces that with the use of a relative path.
=> Replace all uses of `vue-media-annotator` alias under src/ with relative imports

docker/girder_worker.Dockerfile
* fixes #1030 
* fixes another bug introduced by #990 that broke `ldc dev girder_worker_default`
* fixes issue where method sig changes aren't picked up in dev mode.
Tested with tox integration tests.
=> Fix ffmpeg install

client/dive-common/components/Sidebar.vue, client/dive-common/components/TrackSettingsPanel.vue, client/dive-common/components/TypeSettingsPanel.vue, client/dive-common/components/Viewer.vue, client/src/components/TrackList.vue, client/src/components/TypeItem.vue, client/src/components/TypeList.vue
NOTE: this change is significantly easier to read if you ignore template changes, since those are mostly just reorganization.
Changes to height calculation
* Remove expansion panels, really simplified things.
* Move height measurement into `Sidebar.vue`, v-resize, and add a prop to sub-elements telling them how tall they're allowed to be. Sub-components are responsible for figuring out the heights of their header and virtual list section.  I've hard-coded these because IMO it's simpler and no worse than tagging and measuring the DOM.
* Had to do something about the threshold bar since it's dynamic.  I added a prop to the sidebar to indicate that the threshold bar is or is not there, and another hardcoded height I'm not happy about.  But again, it's simple code, so /shrug/
Changes to type …
=> Possible changes to Virtual Type List

client/platform/desktop/frontend/components/ViewerLoader.vue
Fixes #1010 
Looks like it was mistake on my part of using not `!== -1` instead `=== 0` for success.  This update should prevent the viewer from asking to reload if the pipeline fails.
Test Methods:
Simply pick one of the faster pipelines (like `detector_fish_without_motion.pipe`) and temporary change the `include common_fish_detector_with_filter.pipe` or other specification in the file to a non-existing pipe file or setting and it should error.
=> Prevent Desktop Reload on Failed Pipeline

client/dive-common/apispec.ts, client/platform/desktop/backend/ipcService.ts, client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/backend/serializers/nist.ts
* Fixes bug where every json file was being parsed as a NIST file and failing.
* Adds feature to import meta json on desktop for parity with web.
* Removes 2 large blocks of code that were inline-copies of other existing functions.
* Replace `annotationImport` with `dataFileImport` agnostic to the kind of data being ingested to match web logic
* Add tests.
Tested with json tracks, meta files, and CSV.  I don't have any NIST data, but if you tell me where to find some, I can check that too.
fixes #1052
=> Fix #1052 import json and meta json

client/src/track.ts, client/src/use/useTrackStore.ts
Removes a Vue instance from each track instantiation, replace with a simple callback function.
With 100K tracks and 20 types on 20 image frames
* Before: 535-538MB (consistent) memory usage at idle, tops out at 700+ during load
* After: 305-311MB (consistent) memory usage at idle, tops out at 450 during load.
App uses 80MB of memory with no tracks at idle, so this results in about a 50% reduction in dynamic memory usage.
=> [Performance] Reduce Memory footprint for tracks

docker/girder.Dockerfile, server/tests/integration/test_download_extract.py
The virtual env location changed, but the static site wasn't moved. 
Otherwise, the frontend is missing.
=> Poetry fix

client/dive-common/components/RunPipelineMenu.vue, client/platform/desktop/frontend/components/ViewerLoader.vue, client/platform/desktop/frontend/store/dataset.ts
I was still struggling with how this worked, and I went back and looked at the change when `subType` was added as a prop.
https://github.com/Kitware/dive/pull/803
The point of that change was to make it so that this component didn't need to `loadMetadata`: it should be provided with all the filtering information required.  
**Bug**: There was also a bug in the previous behavior where only the first dataset's camera count was checked, so if a 2-cam and 3-cam mult-camera dataset were provided as selected, only the 2-cam option would show up.  In reality, there are no pipelines that accept both those types, so nothing should show up yet.
This change makes `cameraNumbers` a new prop to `RunPipeineMenu` consistent with `subTypeList`, and then adds `cameraCount` to the cache so that it can be …
=> Example without fetching metadata

client/dive-common/components/RunPipelineMenu.vue, client/dive-common/constants.ts, client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/multiCamUtils.ts, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/frontend/components/ViewerLoader.vue, client/platform/desktop/frontend/store/dataset.ts, docker/girder.Dockerfile, server/bucket_notifications/models.py, server/dive_server/__init__.py, server/dive_server/crud.py, server/dive_server/crud_annotation.py, server/dive_server/crud_dataset.py, server/dive_server/crud_rpc.py, server/dive_server/event.py, server/dive_server/views_annotation.py, server/dive_server/views_dataset.py, server/dive_server/views_summary.py, server/dive_utils/__init__.py, server/dive_utils/constants.py, server/dive_utils/models.py, server/dive_utils/serializers/viame.py, server/dive_utils/types.py, server/scripts/migrations.py, server/tests/integration/test_download_extract.py
* This is the largest change and will require the most discussion
* It leaves jobs (pipelines/training/summary) in a broken state fixed by #1068, but I spearated them because the changes are pretty much completely independent, and I thought it would be easier to review by breaking it apart.
This is a soft delete implementation that tolerates data duplication in favor of defending against data loss.
* By modeling the annotations with a `rev_created` and `rev_deleted`, you can check out any point in history.  This is the simplest implementation I could come up with, and should be looked at critically.  I'm open to changing it.
* There is also a revision log collection.  This collection is non-critical (doesn't need to be joined in order to reconstruct history).  It's just a convenience for …
=> Mongo 1: Server side implementation

server/dive_server/crud_annotation.py, server/dive_server/views_annotation.py
This could have been included in #1066 but it's a new feature, so I made it separate.  It provides a read API for rolling back to earlier versions.  
This implementation is naive and I don't want to keep it forever.  It's a true rollback such that it actually deletes rows from the DB.  I would prefer a soft rollback like `git revert` which replays changes in reverse.  But that sounded complicated and I didn't feel like writing it.
=> Mongo 2: Rollback API

server/pyproject.toml
Related issues
* https://github.com/PyCQA/isort/pull/1875
* https://github.com/pypa/virtualenv/issues/2257
* https://github.com/pre-commit/pre-commit/issues/2178
=> Resolve setuptools issue

server/dive_server/crud_rpc.py, server/dive_tasks/tasks.py, server/tests/integration/conftest.py, server/tests/integration/test_zip_uploads.py
* Changes a bit of code related to import dataset folder discovery to support arbitrary depths and cases where the zipfile is constructed in an unusual way.  Sometimes `filenames` doesn't list the directory as its own item, which was breaking stuff.  See this comment for a better description of what was broken: https://github.com/Kitware/dive/pull/1062#pullrequestreview-836459161
* Changes the integration test to parameterize the dataset rather than the user, so it's immediately clear what test case failed.
* Replaces the early return statement in `postprocess` because it makes things easier and you can leave off the "cleanup" routine in the celery task.  The server should be smart enough to detect a zip upload and not go around creating empty annotation files and aux folders when it …
=> Arbitrary depth support for zip imports

server/dive_server/crud_annotation.py, server/dive_server/crud_rpc.py, server/dive_server/event.py, server/dive_server/views_annotation.py, server/dive_server/views_dataset.py, server/dive_tasks/tasks.py, server/dive_tasks/utils.py, server/dive_utils/constants.py, server/dive_utils/models.py, server/dive_utils/types.py, server/scripts/migrations.py, server/tests/integration/test_dataset_download.py, server/tests/integration/test_pipelines.py, server/tests/test_attributes_processor.py, server/tests/test_deserialize_viame_csv.py, server/tests/test_serialize_viame_csv.py, testutils/tracks.json
I think this one is pretty straightforward.
* Switches to TypedDict params for training so that pipelines and training jobs match.
* Generates exports using input revision ID and `urllib.urlretrieve`
=> Mongo 3: Utilize new endpoints in celery

client/dive-common/apispec.ts, client/dive-common/components/Viewer.vue, client/platform/web-girder/api/annotation.service.ts, client/platform/web-girder/api/dataset.service.ts, client/platform/web-girder/router.ts, client/platform/web-girder/views/Clone.vue, client/platform/web-girder/views/ViewerLoader.vue
Adds optional `viewer/:datasetId/rev/:revisionId` to route which loads the dataset from a specified revision.  Whenever this optional route param is used, the UI is placed into the already implementated "read-only" state.
I think the UI needs more clear indication that a previous revision is loaded, what that means, and how to either commit the rollback or return to HEAD, but that seemed out of scope until the rest of the revision history is implemented.  For now, this is more of an easter-egg feature for us.
=> Mongo 4: Client changes to support revisions

client/dive-common/components/ImportAnnotations.vue, client/dive-common/constants.ts, client/platform/desktop/backend/ipcService.ts, client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/constants.ts, client/platform/desktop/frontend/api.ts, client/platform/desktop/frontend/components/Export.vue, client/platform/desktop/frontend/components/ImportDialog.vue, client/platform/web-girder/views/Upload.vue, server/dive_server/crud_dataset.py, server/dive_tasks/tasks.py, server/dive_tasks/utils.py, server/dive_utils/constants.py
fixes #1056
Just started working on it:
Always open to any and all CSS improvments.
Could see an argument for making `metaFileAbsPath: null | string` instead of `metaFileAbsPath?: string`
File Import V-Menu listing supported types and link to documentation:
Upload on Web Including meta.json:
Upload in Desktop with Advanced meta.json section:
Export Configuration Added to Desktop:
=> Meta File Upload

.env.default, docker-compose.yml
This will not cause a change unless enabled.  Local development will continue to use a docker volume.
=> Optional mongodb volume path

client/src/use/useTrackFilters.ts
Low confidence wouldn't work under 0.10 because of a Max comparison.  Switched it to default to 0 for the lower value.
=> fixing default low confidence

client/platform/web-girder/store/Jobs.ts, client/platform/web-girder/store/index.ts, client/platform/web-girder/store/types.ts, client/platform/web-girder/views/DataBrowser.vue, client/platform/web-girder/views/Jobs.vue, client/platform/web-girder/views/JobsTab.vue, server/dive_server/__init__.py, server/dive_server/crud_rpc.py, server/dive_utils/constants.py, server/dive_utils/serializers/viame.py
Expose and centralize what jobs are running on what datasets.
Now, running jobs are visible directly in the data browser.  This will hopefully lead to less confusion about why "Launch annotator' isn't visible during transcoding or what pipelines are running.
Nothing is visible for training yet because training isn't "blocking" anything.
=> Better status indicators for running jobs.

client/dive-common/constants.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/frontend/components/MultiTrainingMenu.vue, client/platform/web-girder/views/RunTrainingMenu.vue, server/dive_tasks/pipeline_discovery.py
fixes #1122 
fixes #1123 
fixes #1121 
- Adds in `.continue` to the filter to dissallowed training configurations.
- Sets the default pipeline in the Desktop version to "train_detector_default"
- Strips the `viame_csv.pipe` name from all of the training configurations in desktop/web
- Adds a persistent hint to the `v-select` which displays the full filename.
I could also but didn't want to modify the `getTrainingConfigs` endpoint.  That could be modified instead of doing all the stripping work on the client.  Instead just a small function (`simplifyTrainingName`) added to constants.ts (I think it's okay because it's a relatively simple function used across desktop/web).  I like that it just provides a list of files and client takes care of the presentation of the names.  If it was …
=> Updating training configurations

client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts
Looks like another +1 for unit tests.  I wanted to add a quick unit test and I think the timing was off (let me know if I'm wrong).  It looks like if you use `utc(Number)` that number needs to be specified in milliseconds (X1000) instead of seconds.  You could do that or you could do `utc(0).seconds(Number)` to get the proper value. 
I also added padding to the JS version so it would match the six digits of the python/web version of `strftime(%f)`
=> Unit Test Addition and Timing modification

client/platform/web-girder/views/Upload.vue, server/dive_tasks/utils.py
fixes #1138 
- When uploading a zip file it provides direct references to the documentation for the Zip files.
- Updated the error message in the log to also reference the zip file documentation.
- Fix some minor bugs with printing out missing images/videos in a zip file.
=> Zip File Documentation and Errors

client/dive-common/components/EditorMenu.vue, client/dive-common/components/Viewer.vue, client/dive-common/store/settings.ts, client/package.json, client/src/components/LayerManager.vue, client/src/components/controls/EventChart.vue, client/src/layers/AnnotationLayers/TailLayer.ts, client/src/layers/BaseLayer.ts, client/src/layers/index.ts, client/src/provides.ts, client/src/types.ts, client/yarn.lock
https://user-images.githubusercontent.com/4214172/151826503-548d208f-9fbb-4cc9-bd3c-0cfd9822a655.mp4
*  **Change interpolated region color indicator to yellow for consistency between tail region and event view**
* Generate tails on-the-fly (relatively) efficiently by using the `track.features` sparse array with `slice()` to extract the region of interest.
* Adds controls for selecting the before and after length, which will affect performance.
* The tail does not indicate empty regions within a track.  Occlusion is not indicated by the line style.  It can be done, but only if we think it's important.  I didn't want a fully transparent line because then the track looks broken -- like it could be multiple tracks.
* Need to test this approach on a diverse group of datasets.
resolves #1114
=> Track Trails

client/platform/web-girder/views/Export.vue, client/platform/web-girder/views/Home.vue, client/platform/web-girder/views/ViewerLoader.vue, server/dive_server/crud_dataset.py, server/dive_server/views_dataset.py, server/tests/integration/test_dataset_download.py
fixes #812 
fixes #925
Updated 20220131:
- Removed the `GET dive_annotation/{id}/export` for an endpoint `GET dive_annotation/export` where an array of `folderIds` is passed in.  Endpoint will now load the multiple folders and pass them to an updated `export_datasets_zipstream`.  If there are multiple folders it names the output `batch_export.zip` if not it will use the single folder's name.
- updated `export_datasets_zipstream` to `export_datasets_zipstream` to support multiple girder folders.  It will then use the settings and zip up the multiple folders instead of a single folder.  Just a minor restructuring of the function to support multiple datasets.
- Client side `platform/web-girder/views/Export.vue`  will now take in an array of folderIds instead of a single one.
- Behavior for a …
=> Batch Export

client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/utils.ts, client/platform/desktop/backend/serializers/viame.ts, server/dive_server/crud.py, server/dive_server/crud_rpc.py, server/dive_utils/serializers/viame.py
fixes #733
* Force reorder under the special condition that no tracks exist.
* Handle errors when images don't exist
Dataset: https://viame.kitware.com/#/viewer/61f95585cf413d9ad2a200f5
CSV:  [output_tracks.csv](https://github.com/Kitware/dive/files/7979793/output_tracks.csv)
Try slight modifications to encounter error conditions (single track annotation, random image name)
=> Fixes #733

client/platform/desktop/backend/serializers/nist.ts, client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts, server/dive_utils/models.py, server/scripts/generateLargeDataset.py, server/tests/test_deserialize_kwcoco_json.py, server/tests/test_deserialize_viame_csv.py, server/tests/test_serialize_viame_csv.py, testutils/attributes.spec.json, testutils/nist.spec.json, testutils/tracks.json, testutils/viame.spec.json
This reconciles differences between web and desktop in the other direction:
* keyframe is not set by default and should _never_ be set, because all frames in a json export are always keyframes.
* interpolate is not set by default
Because these are repeated in every frame, even small datasets will have lots of useless information encoded in these.  keyframe=True is meaningless because interpolated frames are never exported: they only exist at runtime.  interpolate=True can be set, but the default is for them to be false and unset.
This does not change how the annotator saves annotations.  If an annotation is drawn, it will still have these useless values in the "upsert" payload and end up getting saved.  Scrubbing these useless values at save time (either client side or server side) is out …
=> No keyframe or interpolate defaults

client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/serializers/nist.ts, client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts, client/src/track.ts, server/dive_utils/models.py, server/dive_utils/serializers/viame.py, server/scripts/generateLargeDataset.py, server/tests/test_deserialize_kwcoco_json.py, server/tests/test_deserialize_viame_csv.py, server/tests/test_serialize_viame_csv.py, testutils/attributes.spec.json, testutils/nist.spec.json, testutils/tracks.json, testutils/viame.spec.json
fixes #993 
fixes #1152 
- Simple fix involved adding optional `-` specifiers to the RegEx for polygon.  Decided it should be added to head tail points as well and did it in both desktop and python.
- Updated the unit tests to account for negative values.  Doing that I also decided that I wanted unified tests between python and node so I refactored the viame serializers to use the same JSON file.
- Noticed there were discrepancies in the outputs of Python vs Node so I remedied them:
- `fishLength` was always set to `-1` on Node but set to `None`  in Python so I made it so both will set it to `None/undefined` if it equals `-1`
- Node gave each track a `meta:{}` attribute that was never used.  Python didn't read in or create this attribute so I removed the automatic creation from the node …
=> Fixing negative Coordinates in polygons 

client/platform/web-girder/constants.ts, client/platform/web-girder/views/Upload.vue, client/platform/web-girder/views/UploadGirder.vue
This PR updates the regex that is used to strip off filename suffixes when multiple files are being bulk uploaded. The existing regex was too greedy and would strip off everything after the first period in the name; the new one does so only for the last one.
Closes #838.
=> Don't strip off too many periods from bulk uploaded filenames

client/src/components/annotators/ImageAnnotator.vue
fixes #1082 
To Reproduce:
Load a dataset with large images and decent number of tracks like: https://viame.kitware.com/#/viewer/5f52a38d683ae84c2a4f58de
Once the tracks have loaded and before the image has loaded click in the timeline bar or on the video/image scrubber to jump to another frame.  You should see the corresponding error in the console log as well as if you do it on the server it will be shown in sentry.
The Fix:
Simply guarding the `seek` and just in case the `drawImage` functions to make sure they return directly when `data.ready` is false.  If they try to access geoJS map parameters before hand there are errors.
I tried to see if I could get the same problem to occur in Video mode but it looks like it doesn't happen.  Going to log an additional error that is caused by …
=> Fixes Sentry Error #1082 (Cannot read properties of null)

client/dive-common/components/EditorMenu.vue
Gives visibility buttons a static outline to eliminate the 1px shift from vuetify.
=> fix 1px shift on visibilty buttons

client/dive-common/components/DeleteControls.vue, client/dive-common/components/EditorMenu.vue, client/dive-common/components/Viewer.vue, client/dive-common/use/useModeManager.ts
fixes #697 
fixes #1172  (Thanks Mary)
Latest update has changed how this works based on mockups.
Switching between different modes (being Creating/Editing OR rectangle/Poly/Line) will display a tooltip for 3 seconds giving information about the mode like "Hit ESC to exist creation", or "select midpoints to add new points to polygon"
These tooltips are still there when returning to hover over the main title section.
Implementation:
- `useModeManager` has a canary variable used to determine creating vs editing modes and provides that to the `EditorMenu.vue`.  This is a prop in EditorMenu.vue called `editingDetails = 'disabled' | 'Creating' | 'Editing'`.
- There is a computed property called `EditorHeader` which provides the text and coloring for the buttons based on the editing mode and …
=> Clarity into current editing modes

client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts, server/dive_utils/serializers/viame.py, server/tests/test_serialize_viame_csv.py
fixes #1173 
- Adds a check to see if the field is empty when using the image map.  It will skip using the image map if the field is empty.  
- Added another check to make sure that there are no files where it swaps between providing image filenames and not.  This needed to handle both cases of (first row empty, second row populated) and (first row populated, second row empty).  So it will throw an error when it encounters a row which is different than the previous rows.
Note:  I wanted to add tests but the rejection process within the `viame.ts` `parse` function wasn't working well using jest.  I may need to look into this more to figure out how I can add some relevant tests for image ordering and this new error.
=> Fix Empty Image Filenames in CSV

.github/workflows/blank.yml, .github/workflows/release.yml, client/package.json, client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts, client/yarn.lock, server/dive_utils/serializers/viame.py, server/tests/test_serialize_viame_csv.py
Approach is explained in a large comment block in `viame.ts`
fixes #1167
=> Fix image map loading logic on desktop

client/dive-common/components/AttributeInput.vue, client/dive-common/components/AttributesSubsection.vue, client/dive-common/components/ImportAnnotations.vue, client/dive-common/components/RunPipelineMenu.vue, client/dive-common/components/Sidebar.vue, client/dive-common/components/TrackDetailsPanel.vue, client/dive-common/components/Viewer.vue, client/dive-common/vue-utilities/prompt-service/Prompt.vue, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/frontend/components/ViewerLoader.vue, client/platform/web-girder/store/Jobs.ts, client/platform/web-girder/store/types.ts, client/platform/web-girder/views/Home.vue, client/platform/web-girder/views/ViewerLoader.vue, client/src/components/TrackItem.vue, client/src/components/TrackList.vue, client/src/components/TypeEditor.vue, client/src/components/TypeList.vue, client/src/provides.ts, client/src/use/useTrackSelectionControls.spec.ts, client/src/use/useTrackSelectionControls.ts, server/dive_server/crud_rpc.py
fixes #991 
Summary of the user interface changes:
https://user-images.githubusercontent.com/61746913/153610323-298fb684-c170-4da7-a547-c486112f3ad2.mp4
- The Data Browser won't allow pipelines to be run when you have selected a dataset which currently has a running a pipeline
- Within the Annotator when a pipeline is running on the current dataset the system switches to read-only mode and prevents edits and indicates to the user that a pipeline is running
- While the pipeline is running in the pipeline dropdown there is a link to currently running pipeline job data
- Read-only mode has been updated to disable various UI controls and shortcuts (Adding tracks, deleting tracks, editing tracks) and all of these items
- Read Only Mode has it's own indicator below the Dataset Title with some …
=> Current Pipeline Running information

client/dive-common/components/SidebarContext.vue, client/dive-common/components/TypeThreshold.vue, client/dive-common/components/Viewer.vue, client/dive-common/store/context.ts, client/dive-common/use/useRequest.ts, client/platform/desktop/frontend/components/ViewerLoader.vue, client/platform/web-girder/api/annotation.service.ts, client/platform/web-girder/router.ts, client/platform/web-girder/views/Clone.vue, client/platform/web-girder/views/Export.vue, client/platform/web-girder/views/RevisionHistory.vue, client/platform/web-girder/views/ViewerLoader.vue, client/src/layers/BaseLayer.ts, client/src/provides.ts, docs/Web-Version.md, server/dive_server/crud_annotation.py, server/dive_server/views_annotation.py, server/dive_utils/serializers/viame.py
* Adds revision history contextual sidebar, and a button to open it which so far I really dislike.  Feedback needed.
* Clone or download annotations when a past revision is loaded.
Please forgive the random book cover instead of real data.
fixes #1078
=> Revision History UI

client/dive-common/components/ImageEnhancements.vue, client/dive-common/components/Viewer.vue, client/dive-common/store/context.ts, client/src/components/annotators/ImageAnnotator.vue, client/src/components/annotators/VideoAnnotator.vue, client/src/components/controls/Controls.vue, client/src/provides.ts, client/src/types.ts, client/src/use/index.ts, client/src/use/useImageEnhancements.ts, docs/UI-Timeline.md
fixes #1197 
I added in a small basic image enhancement to modify the filter on SVG filter.
I added a context menu because I have a feeling these effects might expand in the future beyond just doing contrast adjustments.  I guess it could be a small pop-up like the playback speed, but I'm guessing that we want to add more stuff in the future to this.
Image/Video Annotators have been modified to accepting an [intercept](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/intercept) as well as a brightness setting.  So you can adjust both to adjust the brightness and contrast of the image.
I created `useImageEnhancments.ts` with the idea that in the future the image enhancements may be more complex with more data being transferred.  That's also why it accepts `markChangesPending`, so …
=> Image enhancements

client/dive-common/components/ConfidenceSubsection.vue, client/dive-common/components/TrackDetailsPanel.vue
fixes #1202
This is the easy/obvious solution I could add quickly to give the user something that worked.  There may be a more ergonomic version that accepts the current top confidence as correct from the track list, but I didn't do that because there's no way to show the user feedback that this has done something, and adding visual feedback will require a bit more thought.
We'll need a way to display on a track list item where `confidence == 1` or not, and then a button or hotkey or something to boost it to 1.  This is related to #614.
I think this PR is a minimal fix that will give users something to provide feedback on.
=> Button to boost confidence to 1.0

client/dive-common/vue-utilities/prompt-service/Prompt.vue
Fixes a bug with the prompt menu, to make sure it properly shows the cancel button when one is specified.
We needed a prompt with confirmation but without a cancel button so it uses the empty '' string for those instance when reloading pipelines.
This fixes it so it properly looks for the negativeButton and ensures that it has a length.
=> fixing prompt

server/dive_server/crud_dataset.py, server/dive_tasks/utils.py, server/tests/integration/test_dataset_operations.py
media downloads for pipelines and training were failing after the ID used for media changed from a file id to an item ID.
=> Fix bug in media pipelines

server/dive_utils/serializers/viame.py
Image sequences with tracks and more than 256 images will fail to load annotations.
I was bamboozled by cpython: https://stackoverflow.com/questions/2239737/is-it-better-to-use-is-or-for-number-comparison-in-python
=> Fix CSV parse

docker/girder.Dockerfile, docker/girder_worker.Dockerfile, server/poetry.lock, server/pyproject.toml, server/tox.ini
* Upgrades to python 3.8 -- Recommend moving to 3.8.13 in your local virtual environment.  3.7 is no longer an active version, and will reach end of life in a year.
* Upgrades most dependencies.  It's been 5 months, and I like to do this about 2 times per year.
Integration and unit tests passing (aside from the failure caused by viame).
=> Upgrade python 3.8, Upgrade python deps

client/platform/web-girder/api/annotation.service.ts, client/platform/web-girder/router.ts, client/platform/web-girder/views/ShareTab.vue, client/platform/web-girder/views/Summary.vue, client/src/use/useStyling.ts, server/dive_server/crud_annotation.py, server/dive_server/crud_dataset.py, server/dive_server/views_annotation.py
Now, individual users can get personalized summaries of the data they have access to.  This summary page can be customized to show summaries for...
1. All datasets to which the user has write access.
2. All datasets that have been "published"
3. All datasets that a user has either read or write access to that have been shared.
Request
`GET http://localhost:8010/api/v1/dive_annotation/labels?published=false&shared=false`
Response Example
``` json
[
{
"_id": "Bull",
"count": 1882,
"datasets": [
{
"id": "62583302bb61f47e1adc5112",
"name": "20070609_SLAP5808_Orig"
}
]
},
{
"_id": "Fem",
"count": 11910,
"datasets": [
{
"id": "62583302bb61f47e1adc5112",
"name": "20070609_SLAP5808_Orig"
},
{
"id": "62583176bb61f47e1adc50d6",
"name": "20171027.214830.290.029136"
}
]
},
{
"_id": …
```
=> Stats Page Support

server/dive_server/crud_dataset.py
There is a bug caused by `published=True, shared=True` that causes this function to return a query that will search for every public dataset, which is exactly the thing we were trying to avoid with this summary feature.
* What it did: `OR(dataset_query, shared_clause, published_clause)`
* What it should have done: `AND(dataset_query, OR(shared_clause, published_clause))`
It will also allow an unprivileged user to inspect labels inside all other user's private datasets IF those datasets are marked with the "published" metadata tag.  This is an edge case that **doesn't actually exist in prod**, but it's definitely an issue. 
Rewrite this function to have a `base_query` that will always be `$and` combined with `optional_query_parts`.
This is required before the stats page can be added again.
=> Fix get_dataset_query

client/dive-common/components/ImportMultiCamDialog.vue, client/src/components/annotators/useMediaController.ts, server/dive_utils/__init__.py, server/dive_utils/serializers/meva.py
A request to have multicamera data unclamp the camera bounds so that linked cameras will behave better when panning around.
There may still be a question of how zooming works where geoJS will unzoom around the location of the mouse cursor instead of the current area's bounds.  That may have to be updated to get this working properly.
=> multicamera unclamping

client/platform/web-girder/views/Jobs.vue, server/dive_server/__init__.py, server/dive_server/views_override.py
Show the size of the job queue to all users.
This is an imperfect solution because when another user in the system creates a job, it won't show up here because User A won't get push notifications about user B's jobs.  It will update for changes in User A's job status, but otherwise might require a page reload to be correct.
fixes #1260
=> Job queue size

client/dive-common/use/useModeManager.ts
Closes #1272 
Issue was caused by using getAnyTrack with a trackId that doesn't exists.
Original intention was that this was being used for creating a track in another camera where the original track already had a trackId.  This code was just grabbing the type of the source camera track to make sure they aligned.
The newTracksettingsAfterLogic when the user is in Continuous detection mode uses a new overrideId by grabbing a new trackId to assign to the new Track.  When in singlecam the new trackId doesn't exist already so you get the error.  Swapping this to `getAnyPossibleTrack` will return an undefined if it is not located and will revert back to the default track type instead of trying to match it up.
https://user-images.githubusercontent.com/61746913/179258517-12de12c3-06f3-43c8-8251-5 …
=> fixing detections afterTrack logic

client/dive-common/components/AttributeEditor.vue, client/dive-common/components/AttributeInput.vue, client/dive-common/components/AttributesSubsection.vue, client/src/use/useAttributes.ts, server/dive_utils/models.py
- models.py updated the attributes for optional `editor` object which can include future visualization options for attributes
- Added in the `color` option for the attribute timeline/filtering tools
- Added selection between input box/slider for numeric attributes
https://user-images.githubusercontent.com/61746913/184219479-56bc1e5d-d2ad-4821-9b73-8820a0cf98d3.mp4
=> Numeric Slider Support

server/dive_server/crud_rpc.py
I was calling `user.get('_id', 'unknown')` forgetting that it is a objectId and not a string.
Wrapping it in `str()` call will fix the issue and allow the button to work again in the admin interface.
=> Fix Admin Job User Directory Reference

client/platform/desktop/backend/native/common.ts
On desktop if you import a configuration file it will overwrite all the annotations for the user at the same time.  This seems to be a bug in the import function that this PR should resolve.
So if you import a configuration json (meta.json) or file which contains the keys it will prevent it from overwriting the current annotations now.
=> Fix Desktop Configuration File Importing

docker/girder.Dockerfile, docker/girder_worker.Dockerfile, server/poetry.lock, server/pyproject.toml
- Older version of poetry we were using (1.1.2) was causing some build errors.
- Updated to the latest version (1.2.0) but it had different behaviors when determining that the currently used python virutalenv was active.
- From the [Poetry Environment Management Docs](https://python-poetry.org/docs/managing-environments/) it should recognize that it is inside of a venv and not create a new one.  It did this properly for the 1.1.2 version but not for 1.2.0.
- To force it to recognize the the virtualenv I had to set the Environment variable manually.
- Additionally, on the worker container, I needed to make sure it did a full copy of the files and didn't use symbolic links for the venv.  The final container for the worker is based off a VIAME GPU algorithms container so it isn't guaranteed …
=> Update Poetry Version

client/dive-common/components/TrackDetailsPanel.vue, client/dive-common/components/Viewer.vue, client/dive-common/use/useModeManager.ts, client/platform/desktop/frontend/components/ImportDialog.vue, client/platform/desktop/frontend/components/Recent.vue, client/src/BaseAnnotationStore.ts, client/src/BaseFilterControls.ts, client/src/CameraStore.ts, client/src/TrackFilterControls.spec.ts, client/src/TrackStore.spec.ts, client/src/components/FilterList.vue, client/src/components/GroupItem.vue, client/src/components/GroupList.vue, client/src/components/TrackList.vue, client/src/provides.ts, client/src/use/useEventChart.ts, client/src/use/useLineChart.ts
A problem involving large data (~130,000 tracks) which included a large amount sub-data (multiple polygon annotations per track) was crashing during loading.
I narrowed down the problem to the fact that the `baseAnnotationStore` which is the basis for the `trackStore` and `groupStore` has a computed property called `sorted` which was passing around a direct copy of each Track.  The sorted property was used to display tracks in the track list, the event timeline, and multiple other areas.  Each time there may need be another computed property based on this list which may require either `forEach` or `map` for all of the values.
Initially I have changed the `sorted` computed property to not sort and create tracks until a call to `setEnableSorting`.  For track lists that are < 20000 I've …
=> Refactor Sorted Annotations

docs/index.md
@zachmullen discovered a bad material icon name on the DIVE front page:
This PR replaces the broken icon specifier with [this one from Fontawesome](https://fontawesome.com/v5/icons/desktop?style=solid&s=solid&f=classic) (which is also part of the mkdocs material theme):
(I don't know why the buttons are blue in my local build, but black in the deployed version.)
=> Use a working "desktop" icon in docs front page

client/platform/web-girder/views/Upload.vue
Not 100% on this change but when uploading a zip file, the progress indicator incorrectly showed "2.13 GB of 18.91 GB remaining" with the first number counting upward, not downward — the word "remaining" was not correct.
=> Fix upload progress indicator label

client/src/components/annotators/ImageAnnotator.vue
Swaps the geoJS renderer from Webgl to Canvas when the image size exceeds 8192 (8k) in any dimension.
WebGL has a maximum texture size and this will allow larger images to be displayed in the renderer.
=> Canvas renderer for large images

client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts, server/dive_server/crud_dataset.py, server/dive_utils/serializers/kwcoco.py, server/dive_utils/serializers/viame.py, server/tests/test_serialize_viame_csv.py
resolves #1329 
Done:
- Frame remapping when images are a subsample of those referenced in a loaded CSV file for electron
- Updated client tests for new errors and formats
- If images referenced in CSV include images in the dataset and they are in the proper order it will allow loading
- Extra images are ignored then
- Logic for this has been updated on Electron version as well as python version
Testing:
- Take a sample dataset like Ehu from the server and copy and create 3 different folders. [Ehu Link](https://viame.kitware.com/#/viewer/5e4c282ba0fc86aa0315cd93)
- The base dataset with all the images
- A subsampled dataset with 20-30 sequential images
- A subsampled dataset with 20-30 non-sequential images
- Take the original annotations.csv file from Ehu and load it into the sequential …
=> SubSample Image Loading

samples/scripts/syncAnnotationsScript.py, samples/scripts/uploadScript.py
This is a script for NOAA to import their mirrored bucket annotations into their system.  I'm going to deliver it directly to them but I feel it should be included in the repo as a reference point for others who may want to utilize similar features of girder-client.
- Allows specifying a GirderId for a root folder and local mounted folder location to mirror.  It will then upload the annotations to the mirrored directory structure in the system.
- ImageSet Structure is :
- ./bucket-name-images/platform/date/ID/imageType/images/Dir0001
- ./bucket-name-images/platform/date/ID/imageType/images/Dir0002
- ./bucket-name-images/platform/date/ID/imageType/images/Dir0003
- Annotation Struture is:
- ./bucket-name-annotations/platform/date/ID/imageType/images/ANNOTATIONS
- …
=> NOAA Upload Script

server/dive_tasks/utils.py
The previous cancellation logic was dependent on the subprocess printing lines.
This update does a 1 minute polling interval where it checks to see if the state is cancelling.
If it is cancelling it will send signals to kill the sub process.  For VIAME it seems that it only responds favorably to a SIGINT signal so that is added.
=> Polling Based Job Cancellation

client/src/components/annotators/ImageAnnotator.vue, client/yarn.lock
I had the logic in there that would toggle to a canvas renderer if the system had a large texture.
Specific issues were occurring when there was  smaller first image so it didn't modify the renderer to canvas instead of webgl.
After talking with the geoJS devs it seems there is minimal performance issues if I just default to the canvas renderer.
=> Switch to Canvas Renderer

client/platform/desktop/backend/serializers/viame.ts
Fixes some ordering issues with sparsed tracks in a CSV.
Specifically if you had sparsely populated tracks it would throw an ordering error.
I.E if you had tracks on frame 1, 3, 5 the logic from before would throw an error about being out of order but that isn't necessarily true.  That logic just checked to make sure that the next frame in each instance was equal to the current frame + 1, we really just want the next frame to be greater than the lower frame and throw and error if it isn't.
To add to this I also did some pre-sorting of the frames.  Annotators kept giving my CSV files that don't have the frame ordering sorted.
=> fix desktop ordering error

client/dive-common/apispec.ts, client/dive-common/components/ImportAnnotations.vue, client/platform/desktop/backend/cli.ts, client/platform/desktop/backend/ipcService.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/serializers/viame.spec.ts, client/platform/desktop/backend/serializers/viame.ts, client/platform/desktop/frontend/api.ts, client/platform/web-girder/api/dataset.service.ts, client/platform/web-girder/api/rpc.service.ts, client/platform/web-girder/views/Export.vue, server/dive_server/crud_rpc.py, server/dive_utils/serializers/viame.py, server/tests/test_attributes_processor.py, server/tests/test_deserialize_viame_csv.py, server/tests/test_serialize_viame_csv.py
- If the frame spacing is more than one frame it swaps to using the mapped image frame number
- If the system fails to sync up the frame numbers with the images it provide a warning instead of erroring out.
=> Frame adjustment

server/dive_server/crud_annotation.py
The set query of None in the revision list was causing a problem where it wouldn't show all revisions.  This fixes that issue.
=> remove set query from revision list

client/dive-common/components/ImportAnnotations.vue, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/serializers/dive.ts, client/platform/desktop/backend/serializers/viame.ts, client/platform/desktop/constants.ts, client/platform/desktop/frontend/api.ts, client/platform/desktop/frontend/components/Export.vue, client/yarn.lock, server/dive_server/crud_dataset.py, server/dive_server/views_annotation.py
Fixes exporting without track.attributes
Adds TrackJSON exporting to desktop version
Incorporates the confidence and type filters for the web TrackJSON exporting.
=> add trackJSON to desktop exporting

client/platform/desktop/backend/serializers/viame.ts, samples/scripts/setAnnotationFPS.py, server/dive_server/crud_rpc.py, server/dive_utils/models.py, server/dive_utils/serializers/viame.py, server/tests/test_attributes_processor.py, server/tests/test_deserialize_viame_csv.py, server/tests/test_serialize_viame_csv.py
- Sets Server to utilize the # metadata, fps: 30 for the FPS when uploading a CSV.
- Sets the Desktop to also utilize the fps in metadata as well.
- Finalizes a script to set the FPS on multiple subfolders using a python script
TODO:
Made a decision to delay a UI tool for setting annotation FPS to another PR.
=> reading FPS from CSV Metadata

client/dive-common/apispec.ts, client/dive-common/components/ImportButton.vue, client/platform/desktop/backend/ipcService.ts, client/platform/desktop/backend/native/common.spec.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/utils.ts, client/platform/desktop/frontend/api.ts, client/platform/desktop/frontend/components/BulkImportDialog.vue, client/platform/desktop/frontend/components/ImportDialog.vue, client/platform/desktop/frontend/components/Recent.vue
Closes #1455 
Allows for bulk importing of datasets with a new "Bulk Import" button. This is done by recursively searching for datasets, wrapping the existing import sequence. If a directory fails the import sequence, the function will recurse into that directory.
=> Implement bulk import

client/dive-common/components/RunPipelineMenu.vue, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/viame.ts
Exposes filter and transcode pipelines to the client. Results from these jobs are placed in the job work directory.
=> Add filter and transcode pipelines

server/dive_server/event.py
large-image assetstore processing
=> large-image-processing

client/dive-common/apispec.ts, client/platform/desktop/backend/ipcService.ts, client/platform/desktop/backend/native/common.ts, client/platform/desktop/backend/native/linux.ts, client/platform/desktop/backend/native/utils.ts, client/platform/desktop/backend/native/viame.ts, client/platform/desktop/backend/native/windows.ts, client/platform/desktop/constants.ts, client/platform/desktop/frontend/api.ts, client/platform/desktop/frontend/components/Jobs.vue, client/platform/desktop/frontend/components/MultiTrainingMenu.vue, client/platform/web-girder/App.vue, client/platform/web-girder/api/rpc.service.ts, client/platform/web-girder/router.ts, client/platform/web-girder/views/Export.vue, client/platform/web-girder/views/Home.vue, client/platform/web-girder/views/Jobs.vue, client/platform/web-girder/views/NavigationBar.vue, client/platform/web-girder/views/TrainedModels.vue, server/dive_server/crud_rpc.py, server/dive_server/views_rpc.py, server/dive_tasks/tasks.py, server/dive_utils/types.py
The main objective of this PR was to add a 'ONNX export' button to export trained models on the platform.
Changes:
- Export to ONNX function is available on Dive Web & Desktop. 
- Added a tab to list, delete and export all trained pipelines. 
- Added the possibility to download single or multiple files from the browser on Dive web.
- Fixed alignment issue on Jobs list on Dive web.
Web:
Desktop:
On Desktop, you can directly select the location where you want to save the ONNX model.
On Web, the exported model will appear in the original model directory. You can click on the eye in the Job list to go directly there.
=> [feature] ONNX Export

client/platform/desktop/backend/native/common.ts
Resolves an issue where training configuration files wouldn't show up because of mistake in #1376 with regards to the regex patterns for the allowed items
=> fix desktop training config Regex Patterns

client/platform/desktop/frontend/components/MultiPipeline.vue, client/platform/desktop/frontend/components/NavigationBar.vue, client/platform/desktop/frontend/components/PipelinePage.vue, client/platform/desktop/router.ts
Fix #1512
Following the precedent of the Multi-Training tab, a new tab has been added to the Dive Desktop navigation bar, called "Pipeline."
This tab contains an interface similar to that of the multi-training interface, but with the ability to run a specified pipeline over multiple datasets.
This is handled by a simple dropdown menu. This must be done first to enable the pipeline select to become enabled.
_Limitation: The pipeline types "2-cam" and "3-cam" are filtered out for now to reduce the complexity of selecting datasets._
Once a pipeline type is chosen, the "Pipeline" dropdown will allow users to select a specific pipeline of that type. Once this is done, the available datasets appear for selection. 
Because the pipeline/type pipeline are chosen first, we have additional control …
=> Add bulk pipeline interface

client/dive-common/components/ControlsContainer.vue, client/dive-common/components/Viewer.vue, client/src/components/ImageEnhancements.vue, client/src/components/annotators/ImageAnnotator.vue, client/src/components/annotators/LargeImageAnnotator.vue, client/src/components/annotators/VideoAnnotator.vue, client/src/components/controls/Controls.vue, client/src/provides.ts, client/src/use/useImageEnhancements.ts, client/yarn.lock
Solves part of #1510 
- Updates image enhancements to have independent sliders for:
- Brightness
- Contrast
- Saturation
- Sharpen
- Sharpen is a little different because it's using a FeConvolveMatrix with the nearest pixels to attempt a similar effect to sharpening.
- imageEnhancementOutputs is a collection of the above values and is passe to the annotators for implementation inthe SVG filters
- isDefaultImage is true when the default values are being used
- This is used to provide a little orange dot at the bottom right of the imageEnhancements Icon/Button.
A Subsquent PR is going to hook this data into the saving system where it will be saved similar to the confidence threshold.  This would allow anyone to adjust the image settings and have it persist so others see the same thing. …
=> Advanced image enhancements
